{include file="header.phtml"}

{assign var='editAliasParams' value="open: true, iframe: true, transition: 'elastic', width: '750px', height: '500px'"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Aliases {if $domain} for {$domain.domain} {if $domain.aliases neq 0}({$domain->countAliases()}/{$domain.aliases}){/if}{/if}</h1>
    </div>



{ViMbAdmin_Messages}

<label><input type="checkbox" name="ima" id="ima" value="1" {if $includeMailboxAliases}checked="checked" {/if}/> Include mailbox aliases</label>

<br/>

<table id="domain_aliases_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Address</th>
            <th>Domain</th>
            <th>Active</th>
            <th>Goto</th>
            <th>
                <button onclick="$.fn.colorbox({ href:'{genUrl controller='alias' action='edit' did=$domainModel.id}', {$editAliasParams} });">Add Alias</button>
            </th>
        </tr>
    </thead>
    <tbody>
    {foreach $aliases as $oneAlias}
        <tr id="alias_{$oneAlias.id}">
            <td>{$oneAlias.address}</td>
            <td>{$oneAlias.domain}</td>
            <td>
                <div id="throb-toggle-active-{$oneAlias.id}" style="float: right;"></div>
                <span id="toggle-active-{$oneAlias.id}" class="btn btn-mini {if $oneAlias.active}btn-success{else}btn-danger{/if}">{$oneAlias.active|yesno}</span>
            </td>
            <td class="OSSTooltip-bl-tl" title="{$oneAlias.goto}">{$oneAlias.goto|shorten:50}</td>
            <td>
                <button class="btn btn-mini" onclick="$.fn.colorbox({ href:'{genUrl controller='alias' action='edit' alid=$oneAlias.id}', {$editAliasParams} });">Edit</button>
                <button class="btn btn-mini" onclick="deleteAlias({$oneAlias.id});">Delete</button>
            </td>
        </tr>
    {/foreach}
    </tbody>
</table>

<br />
<br />
<br />

<a class="btn" href="{genUrl controller='domain' action='list'}">Back to domains</a>

{include file='alias/js/list.js'}
</div>
{include file="footer.phtml"}
