<div id="form_div_edit_alias">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

          <fieldset class="control-group" id="div-form-password">
    	    <label for="local_part" class="control-label">
	    	    	Address
                    <span class="label" rel="popover" data-content="You can alias an entire domain by leaving the address field / local part blank." data-title="Domain Aliases" data-placement="left">?</span>
	    	</label>
    	    <div id="div-controls-{$element->local_part->getId()}" class="controls">
    		    <div class="input-append" style="float: left">
    		        {$element->local_part}
        		    {if !isset( $domain ) || !$domain }
    		            <span class="btn" style="margin-left: -5px; -webkit-border-radius: 0 0 0 0; -moz-border-radius: 0 0 0 0; border-radius: 0 0 0 0;">@</span>
		            {else}
		                <span class="add-on" style="margin-left: -5px;">@{$domain->domain}</span>
		                <div style="display: none;">{$element->domain}</div>
		            {/if}
    		    </div>
    		    {if !isset( $domain ) || !$domain}
    		        {$element->domain}
		        {/if}
    	    </div>
    	    {if $element->local_part->getMessages()}
					<script type="text/javascript">
						$( '#{$element->local_part->getId()}' ).addClass( 'error' );
						$( '#div-form-{$element->local_part->getId()}' ).addClass( 'error' );
					</script>
				{/if}
				<p id="help-{$element->local_part->getId()}" class="help-block">
					{if $element->local_part->getMessages()}
    					{foreach from=$element->local_part->getMessages() item=messages}
        					{foreach from=$messages item=msg}
            					{$msg}<br />
        					{/foreach}
    					{/foreach}
					{/if}
				</p>

				{if $element->domain->getMessages()}
					<script type="text/javascript">
						$( '#{$element->domain->getId()}' ).addClass( 'error' );
						$( '#div-form-{$element->domain->getId()}' ).addClass( 'error' );
					</script>
				{/if}
				<p id="help-{$element->domain->getId()}" class="help-block">
					{if $element->domain->getMessages()}
    					{foreach from=$element->domain->getMessages() item=messages}
        					{foreach from=$messages item=msg}
            					{$msg}<br />
        					{/foreach}
    					{/foreach}
					{/if}
				</p>
    	</fieldset>
    	{include file='form/element-checkbox.phtml' ielement=$element->active}

        <fieldset class="control-group" id="div-form-goto">
            <label for="goto" class="control-label">
                {$element->goto->getLabel()}
            </label>
            <div class="controls" id="div-controls-goto">
                <div class="input-append" id="goto-div-0">
    		        <input type="text" id="goto_empty" autocomplete="off" name="goto[]" value="" size="40" title="Goto" />
    		        <span id="goto-btn-0" title="Add go to" class="btn add-on" onclick="addGoto();" style="margin-left: -5px;">
                        <i class="icon-plus"></i>
                    </span>
    		    </div>
		    {if $element->goto->getMessages()}
				<script type="text/javascript">
					$( '#{$element->goto->getId()}' ).addClass( 'error' );
					$( '#div-form-{$element->goto->getId()}' ).addClass( 'error' );
				</script>
			{/if}
            <p id="help-goto" class="help-block">
                {if $element->goto->getMessages()}
					{foreach from=$element->goto->getMessages() item=messages}
    					{foreach from=$messages item=msg}
        					{$msg}<br />
    					{/foreach}
					{/foreach}
				{/if}
			</p>
            </div>
        </fieldset>

        {if !isset($modal) || !$modal}
        <fieldset class="form-actions">
            <a class="btn" type="button" href="{genUrl controller='alias' action='list'}" value="Cancel" >Cancel</a>
            <input class="btn btn-primary" type="submit" id="{$element->save->getId()}" value="{$element->save->getLabel()}" />
        </field>
        {/if}
    </form>

    <script type="text/javascript">

    $(document).ready(function()
    {
        $( '#domain' ).chosen();

        if( $( '#domain_chzn' ).css( "width" ).length < 5 )
        {
            $( '#domain_chzn' ).css( "width", "150px" );
            $( '.chzn-drop' ).css( "width", "148px" );
            $( '.chzn-search >input' ).css( "width", "110px" );
        }

        $("[rel=popover]").popover();

    }); // document onready

    </script>

</div> <!-- #form_div_edit_alias -->
