To whom it may concern,

Your new administrator account on your ViMbAdmin installation has been created.

Your login details are:

    Username: {$username}
    Password: {$password}

You can log into ViMbAdmin by browsing to:

    {genUrl}


Plesase ensure you keep up with new release announcements and security issues by subscribing to:

    https://groups.google.com/forum/#!forum/vimbadmin-announce

Kind regards,
{$options.server.email.name}
