To whom it may concern,

An administrator account has been created for you on the ViMbAdmin
installation by {$identity.admin.username}.

Your login details are:

    Username: {$username}
    Password: {$password}

You can log into ViMbAdmin by browsing to:

    {genUrl}


Plesase ensure you keep up with new release announcements and security issues by subscribing to:

    https://groups.google.com/forum/#!forum/vimbadmin-announce


Kind regards,
{$options.server.email.name}
