<div id="form_div_edit_domain">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="default_form">

        <table style="height: 250px;">
            <tr>
                <td valign="top" height="100%">
                    <table id="basic_options">
                        <tr>
                            <td class="right bold valign_top">{$element->domain->getLabel()}</td>
                            <td>
                                {$element->domain}
                                {include file='form_element_errors.phtml' pTheElement=$element->domain}
                            </td>
                        </tr>
                        <tr>
                            <td class="right bold">{$element->description->getLabel()}</td>
                            <td>
                                {$element->description}
                                {include file='form_element_errors.phtml' pTheElement=$element->description}
                            </td>
                        </tr>
                        <tr>
                            <td class="right bold"><label for="{$element->backupmx->getId()}" class="inline">{$element->backupmx->getLabel()}</label></td>
                            <td>{$element->backupmx}</td>
                        </tr>
                        <tr>
                            <td class="right bold"><label for="{$element->active->getId()}" class="inline">{$element->active->getLabel()}</label></td>
                            <td>{$element->active}</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><button onclick="$('#advanced_options').toggle('fast'); return false;">Advanced</button></td>
                        </tr>
                    </table> <!-- #basic_options -->
                </td>
                <td valign="top" height="100%">
                    <table id="advanced_options" class="dontdisplay">
                        <tr>
                            <td class="right bold">{$element->aliases->getLabel()}</td>
                            <td>
                                {$element->aliases}
                                {include file='form_element_errors.phtml' pTheElement=$element->aliases}
                            </td>
                        </tr>
                        <tr>
                            <td class="right bold">{$element->mailboxes->getLabel()}</td>
                            <td>
                                {$element->mailboxes}
                                {include file='form_element_errors.phtml' pTheElement=$element->mailboxes}
                            </td>
                        </tr>
                        <tr>
                            <td class="right bold">{$element->maxquota->getLabel()}</td>
                            <td>
                                {$element->maxquota}
                                {include file='form_element_errors.phtml' pTheElement=$element->maxquota}
                            </td>
                        </tr>
                        <tr>
                            <td class="right bold">{$element->quota->getLabel()}</td>
                            <td>
                                {$element->quota}
                                {include file='form_element_errors.phtml' pTheElement=$element->quota}
                            </td>
                        </tr>
                        <tr>
                            <td class="right bold">{$element->transport->getLabel()}</td>
                            <td>
                                {$element->transport}
                                {include file='form_element_errors.phtml' pTheElement=$element->transport}
                            </td>
                        </tr>
                    </table> <!-- #advanced_options -->
                </td>
            </tr>
        </table>

        <input type="button" onclick="parent.$.fn.colorbox.close();" value="Cancel" />
        &nbsp;
        <input type="submit" value="{$element->save->getLabel()}" />
    </form>

</div> <!-- #form_div_edit_domain -->

<script type="text/javascript"> /* <![CDATA[ */

    $(document).ready(function()
    {
        $('#{$element->backupmx->getId()}').bind('change', function() {
            $('#advanced_options').toggle('fast');
        });
    }); // document onready

/* ]]> */ </script>
