
<form action="{$element->getAction()}"
      method="{$element->getMethod()}"
      enctype="{$element->getAttrib('enctype')}"
      id="{$element->getId()}"
      name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
      {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
      class="form-horizontal">


    <div class="row-fluid">
        <div class="span6">
            {include file='form/element-input.phtml' ielement=$element->domain}
            {include file='form/element-textarea.phtml' ielement=$element->description}
            {include file='form/element-checkbox.phtml' ielement=$element->backupmx}
            {include file='form/element-checkbox.phtml' ielement=$element->active}
            <br/>
        </div>
        <div class="span6">
            <div id="advanced_options" style="display: none">
                {include file='form/element-input.phtml' ielement=$element->aliases}
                {include file='form/element-input.phtml' ielement=$element->mailboxes}
                {include file='form/element-input.phtml' ielement=$element->maxquota}
                {include file='form/element-input.phtml' ielement=$element->quota}
                {include file='form/element-input.phtml' ielement=$element->transport}
            </div>
        </div>
    </div>

    {if !isset($modal) || !$modal }
    <fieldset class="form-actions">
        <span class="btn" id="toogle_advanced">Advanced</span>
        <button class="btn" onclick="parent.$.fn.colorbox.close();">Cancel</button>
        <input class="btn btn-primary" type="submit" value="{$element->save->getLabel()}" />
    </fieldset>
    {/if}
</form>

<script type="text/javascript">

    $(document).ready(function()
    {
        $('#toogle_advanced').bind('click', function() {
            $('#advanced_options').toggle('fast');
        });
    }); // document onready

</script>
