<style type="text/css">

/*
The following fixes png-transparency for IE6.
It is also necessary for png-transparency in IE7 & IE8 to avoid 'black halos' with the fade transition

Since this method does not support CSS background-positioning, it is incompatible with CSS sprites.
Colorbox preloads navigation hover classes to account for this.

!! Important Note: AlphaImageLoader src paths are relative to the HTML document,
while regular CSS background images are relative to the CSS document.
*/
.cboxIE #cboxTopLeft
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderTopLeft.png', sizingMethod='scale');
{rdelim}

.cboxIE #cboxTopCenter
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderTopCenter.png', sizingMethod='scale');
{rdelim}

.cboxIE #cboxTopRight
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderTopRight.png', sizingMethod='scale');
{rdelim}

.cboxIE #cboxBottomLeft
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderBottomLeft.png', sizingMethod='scale');
{rdelim}

.cboxIE #cboxBottomCenter
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderBottomCenter.png', sizingMethod='scale');
{rdelim}

.cboxIE #cboxBottomRight
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderBottomRight.png', sizingMethod='scale');
{rdelim}

.cboxIE #cboxMiddleLeft
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderMiddleLeft.png', sizingMethod='scale');
{rdelim}

.cboxIE #cboxMiddleRight
{ldelim}
    background:transparent;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{genUrl}/images/colorbox/internet_explorer/borderMiddleRight.png', sizingMethod='scale');
{rdelim}

</style>
