    </div> <!-- #main -->

{* **************************************************************************

 ===============================
 THINKING OF EDITING THE FOOTER?
 ===============================

Open Solutions and our staff have put a lot of time and effort into both
developing this web application and making it fit for public release under
the GPL license.

As such, we would appreciate and request you leave our copyright message and
link to our site intact in the footer so that we may in some small way
benefit from this application.

Please also consider supporting our worthwhile charity:

    http://www.barnardos.ie/

*************************************************************************** *}

{if !isset($inColorBox) || !$inColorBox}
<div id="footer">
    <div id="footer-copy">
        V{ViMbAdmin_Version::VERSION}.
        Copyright &copy; 2011 {if $smarty.now|date_format:"%Y" neq 2011}- {$smarty.now|date_format:"%Y"}{/if} <a href="http://www.opensolutions.ie/" target="_blank" title="Open Source Solutions Limited">Open Source Solutions Limited</a>.
        The Program is provided AS IS, without warranty. Licensed under <a href="http://www.gnu.org/licenses/gpl-3.0-standalone.html" target="_blank" title="GNU GPL v3">GNU GPL v3</a>.
        <a href="http://www.opensolutions.ie/open-source/vimbadmin/donate" target="_blank" title="Barnardos Children's Charity, Ireland">Support our Charity</a>.
    </div>
</div>
{/if}

</div> <!-- #container -->

<script type="text/javascript"> /* <![CDATA[ */

    jQuery(document).ready(function()
    {
        jQuery('ul.sf-menu').superfish({
            delay: 200,
            animation: { opacity: 'show' },
            speed: 'fast',
            disableHI: true
        });
    });

/* ]]> */ </script>

</body>

</html>
