
{* **************************************************************************

 ===============================
 THINKING OF EDITING THE FOOTER?
 ===============================

Open Solutions and our staff have put a lot of time and effort into both
developing this web application and making it fit for public release under
the GPL license.

As such, we would appreciate and request you leave our copyright message and
link to our site intact in the footer so that we may in some small way
benefit from this application.

*************************************************************************** *}

{if !isset($inColorBox) || !$inColorBox}

    <div id="modal_dialog" class="modal hide fade"> </div>
    <footer>

        {if $smarty.const.APPLICATION_ENV == 'vagrant'}
            <div class="alert alert-warning">
            <p>
                <strong>
                    VIMBADMIN IS RUNNING IN VAGRANT (DEVELOPMENT) MODE AND IS NOT FIT FOR PRODUCTION USE!
                </strong>
            </p>
            </div>
        {/if}

        <p>
            Copyright &copy; 2011 - {$smarty.now|date_formatter:"%Y"} <a href="http://www.opensolutions.ie/" target="_blank" title="Open Source Solutions Limited">Open Source Solutions Limited</a>.
            This Program is provided AS IS, without warranty.
        </p>
        <p>
            <a href="http://www.vimbadmin.net/">ViMbAdmin</a>
                <a href="https://github.com/opensolutions/ViMbAdmin/releases">v{ViMbAdmin_Version::MILESTONE}</a>.
            Licensed under the <a href="http://www.gnu.org/licenses/gpl-3.0-standalone.html" target="_blank" title="GNU GPL v3">
                GNU General Public License V3
            </a>.
        </p>

        <p>
            Keep up with
            <span class="label label-info">
                <a class="aplain" href="http://www.opensolutions.ie/blog/category/vimbadmin/">ViMbAdmin</a>
            </span>
        	&nbsp;|&nbsp;
            Get the source at
            <span class="label label-info">
                <a class="aplain" href="https://github.com/opensolutions/ViMbAdmin">GitHub</a>
            </span>
            &nbsp;|&nbsp;
            Learn more about
            <span class="label label-info">
                <a class="aplain" href="http://www.opensolutions.ie/">Open Solutions</a>
            </span>
            &nbsp;|&nbsp;
            <span class="label label-info">
                <a class="aplain" href="https://groups.google.com/forum/#!forum/vimbadmin-announce">Announcements</a>
            </span>
            and
            <span class="label label-info">
                <a class="aplain" href="https://groups.google.com/forum/#!forum/vimbadmin-discuss">Discussion</a>
            </span>
            Mailing Lists
    	</p>


    </footer>

{/if}

</div> <!-- .container -->

</body>

</html>
