{if isset( $config.use_minified_css ) and $config.use_minified_css}
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/min.bundle-v12.css" />
{else}
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/110-jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/130-colorbox.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/300-chosen.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/800-bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/810-bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/890-override_container_app.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/895-bootstrap-override.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/920-style.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/930-popup.css" />
{/if}
