<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>ViMbAdmin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="Content-Language" content="en" />

    <meta name="description" content="ViMbAdmin" />
    <meta name="keywords" content="ViMbAdmin" />
    <meta name="author" content="www.opensolutions.ie" />
    <meta name="owner" content="www.opensolutions.ie" />
    <meta name="robots" content="index, follow" />

    <link rel="shortcut icon" type="image/x-icon" href="{genUrl}/favicon.ico" />
    <link rel="shortcut icon" type="image/ico" href="{genUrl}/favicon.ico" />
    <link rel="icon" type="image/x-icon" href="{genUrl}/favicon.ico" />

    {include file='header-js.phtml'}
    {include file='header-css.phtml'}

{if isset($inColorBox) && $inColorBox}
    {if !$options.mini_css}
        <link rel="stylesheet" type="text/css" href="{genUrl}/css/930-popup.css" />
    {else}
        <link rel="stylesheet" type="text/css" href="{genUrl}/css/min.930-popup.css" />
    {/if}
{/if}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {include file="colorbox.css.phtml"}
</head>

<body>

{if !isset($inColorBox) || !$inColorBox}
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="{genUrl}">ViMbAdmin{if not $hasIdentity} :: <em>Virtual Mailbox Administration</em>{/if}</a>

                    <div class="nav-collapse">
                        {if $hasIdentity}
                            <ul class="nav">
                                <li {if $controller eq 'domain'}class="active"{/if}>
                                    <a href="{genUrl controller='domain'}" title="Domains">Domains</a>
                                </li>
                                <li {if $controller eq 'mailbox'}class="active"{/if}>
                                    <a href="{genUrl controller='mailbox'}" title="Mailboxes">Mailboxes</a>
                                </li>
                                <li {if $controller eq 'alias'}class="active"{/if}>
                                    <a href="{genUrl controller='alias'}" title="Domains">Aliases</a>
                                </li>
                                <li {if $controller eq 'log'}class="active"{/if}>
                                    <a href="{genUrl controller='log'}" title="Logs">Logs</a>
                                </li>
                                {if $hasIdentity and $identity.admin->isSuper()}
                                    <li {if $controller eq 'admin'}class="active"{/if}>
                                        <a href="{genUrl controller='admin'}" title="Administrators">Administrators</a>
                                    </li>
                                {/if}
                                <li>
                                    <a id="modal-dialog-your_password" href="{genUrl controller='admin' action='password' aid=$identity.admin.id modal=true}">Password</a>
                                </li>
                                 <li {if $action eq 'about'}class="active"{/if}>
                                    <a href="{genUrl controller='index' action='about'}" title="About">About</a>
                                </li>
                            </ul>
                            <ul class="nav pull-right">
                                <li>
                                    <a href="{genUrl controller='auth' action='logout'}" title="Logout">Logout</a>
                                </li>
                            </ul>
                        {else}
                            <ul class="nav">
                                <li {if $action eq 'about'}class="active"{/if}>
                                    <a href="{genUrl controller='index' action='about'}" title="About">About</a>
                                </li>
                            </ul>
                            <ul class="nav pull-right">
                                <li>
                                    <a href="{genUrl controller='auth' action='login'}" title="Login">Login</a>
                                </li>
                            </ul>
                        {/if}

                    </div><!--/.nav-collapse -->

            </div>
        </div>
    </div>
{/if}


<div class="container">
