<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>ViMbAdmin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="Content-Language" content="en" />

    <meta name="description" content="ViMbAdmin" />
    <meta name="keywords" content="ViMbAdmin" />
    <meta name="author" content="www.opensolutions.ie" />
    <meta name="owner" content="www.opensolutions.ie" />
    <meta name="robots" content="index, follow" />

    <link rel="shortcut icon" type="image/x-icon" href="{genUrl}/favicon.ico" />
    <link rel="shortcut icon" type="image/ico" href="{genUrl}/favicon.ico" />
    <link rel="icon" type="image/x-icon" href="{genUrl}/favicon.ico" />

{if !$options.mini_js}
    <script type="text/javascript" src="{genUrl}/js/100-jquery.js"></script>
    <script type="text/javascript" src="{genUrl}/js/110-jquery-ui.js"></script>
    <script type="text/javascript" src="{genUrl}/js/120-jquery.validate.js"></script>
    <script type="text/javascript" src="{genUrl}/js/130-jquery.colorbox.js"></script>
    <script type="text/javascript" src="{genUrl}/js/150-jquery.datatables.js"></script>
    <script type="text/javascript" src="{genUrl}/js/151-jquery.datatables.ext.js"></script>
    <script type="text/javascript" src="{genUrl}/js/800-superfish.js"></script>
    <script type="text/javascript" src="{genUrl}/js/900-vimbadmin.validate.js"></script>
    <script type="text/javascript" src="{genUrl}/js/901-vimbadmin.functions.js"></script>
    <script type="text/javascript" src="{genUrl}/js/902-vimbadmin.tooltip.js"></script>
    {else}
    <script type="text/javascript" src="{genUrl}/js/min.bundle.js"></script>
{/if}

{if !$options.mini_css}
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/110-jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/130-colorbox.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/150-jquery-datatables.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/800-bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/810-bootstrap-responsive.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/890-override_container_app.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/910-menu.css" />
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/920-style.css" />
{else}
    <link rel="stylesheet" type="text/css" href="{genUrl}/css/min.bundle.css" />
{/if}

{if isset($inColorBox) && $inColorBox}
    {if !$options.mini_css}
        <link rel="stylesheet" type="text/css" href="{genUrl}/css/930-popup.css" />
    {else}
        <link rel="stylesheet" type="text/css" href="{genUrl}/css/min.930-popup.css" />
    {/if}
{/if}

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {include file="colorbox.css.phtml"}
</head>

<body>

{if !isset($inColorBox) || !$inColorBox}
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="#">ViMbAdmin{if not $hasIdentity} :: <em>Virtual Mailbox Administration</em>{/if}</a>

                {if $hasIdentity}
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                {/if}
            </div>
        </div>
    </div>
{/if}


<div class="container">

