{assign var='changePwdParams' value="open: true, iframe: true, transition: 'elastic', width: '700px', height: '270px'"}

        <div id="topmenu">
            <ul class="sf-menu">
                <li><a href="{genUrl controller='domain'}" title="Domains">Domains</a></li>
                <li><a href="{genUrl controller='mailbox'}" title="Mailboxes">Mailboxes</a></li>
                <li><a href="{genUrl controller='alias'}" title="Domains">Aliases</a></li>
                <li><a href="{genUrl controller='log'}" title="Logs">Logs</a></li>
            {if $hasIdentity and $identity.admin->isSuper()}
                <li><a href="{genUrl controller='admin'}" title="Administrators">Administrators</a></li>
            {/if}
                <li><a href="#" onclick="$.fn.colorbox({ href:'{genUrl controller='admin' action='password' aid=$identity.admin.id}', {$changePwdParams} });">Password</a></li>
                <li><a href="{genUrl controller='auth' action='logout'}" title="Logout">Logout</a></li>
            </ul>
        </div> <!-- #topmenu -->
