<div id="form_div_login">
    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="default_form">

        <label>{$element->username->getLabel()}</label>
        {$element->username}
        {include file='form_element_errors.phtml' pTheElement=$element->username}

        <label>{$element->password->getLabel()}</label>
        {$element->password}
        {include file='form_element_errors.phtml' pTheElement=$element->password}

        <br />

        <input type="submit" value="{$element->login->getLabel()}" />
    </form>

</div> <!-- #form_div_login -->
