<div id="form_div_login">
<form action="{$element->getAction()}"
      method="{$element->getMethod()}"
      enctype="{$element->getAttrib('enctype')}"
      id="{$element->getId()}"
      name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
      {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
      class="form-horizontal">

{include file='form/element-input.phtml' ielement=$element->username}
{include file='form/element-input.phtml' ielement=$element->password}
                

<fieldset class="form-actions">
    <input class="btn btn-success" type="submit" value="Login" />
    &nbsp;&nbsp;&nbsp;&nbsp;
    <a class="btn" href="{genUrl controller="auth" action="password-reset"}">Lost Password</a>
</fieldset>


</form>

</div> <!-- #form_div_login -->
