<form action="{$element->getAttrib( 'action' )}"
    method="{$element->getMethod()}"
    enctype="{$element->getAttrib('enctype')}" id="{$element->getId()}"
    name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
    class="{$element->getAttrib( 'class' )}"
    {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
>
<fieldset id="{$element->getId()}" horizontal="1">

    {$element->username}

    {if isset( $useCaptcha ) && $useCaptcha}
        {$element->captchaid}
        {$element->requestnewimage}

        <fieldset class="control-group">
            <label></label>
            <div class="controls">
                <img id="captchaimage" src="" alt="CAPTCHA image" title="CAPTCHA - click on the image to request new text" />
            </div>
        </fieldset>

        {$element->captchatext}
    {/if}

    <div class="form-actions">
        {$element->login}
        {$element->getDisplayGroup( "zfBootstrapFormActions" )->getElement( "return_to_login" )}
    </div>


</fieldset>

</form>
