<div id="form_div_password_reset">
    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

        {include file='form/element-input.phtml' ielement=$element->username}

        <fieldset class="form-actions">
            <input class="btn btn-primary" type="submit" value="{$element->reset->getLabel()}" />
        </fieldset>
    </form>
</div> <!-- #form_div_password_reset -->
