<div id="form_div_password_reset">
    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="default_form">

        <label>{$element->username->getLabel()}</label>
        {$element->username}
        {include file='form_element_errors.phtml' pTheElement=$element->username}

        <br />

        <input type="submit" value="{$element->reset->getLabel()}" />
    </form>
</div> <!-- #form_div_password_reset -->
