<div id="form_div_edit_admin">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

        {include file='form/element-input.phtml' ielement=$element->domain}

        {if !isset($modal) || !$modal}
        <fieldset class="form-actions">
            <a class="btn" href="{genUrl controller='admin' action='domains' aid={$element->adminId->getValue()}}">Cancel</a>
            <input class="btn btn-primary" type="submit" id="{$element->save->getId()}" value="{$element->save->getLabel()}" />
        </fieldset>
        {/if}
</div> <!-- #form_div_edit_mailbox -->
