<form action="{genUrl controller="user" action="change-password"}"
      method="{$element->getMethod()}"
      enctype="{$element->getAttrib('enctype')}"
      id="{$element->getId()}"
      class="form-horizontal"
      name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
      {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
>

    {include file='form/element-input.phtml' ielement=$element->current_password}
    {include file='form/element-input.phtml' ielement=$element->password}
    {include file='form/element-input.phtml' ielement=$element->confirm_password}

    {if !isset($modal) || !$modal}
        <fieldset class="form-actions">
            <input type="submit" class="btn btn-primary" value="Change My Password" />
        </fieldset>
    {/if}
</form>
