<div id="form_div_edit_admin">

<form action="{$element->getAction()}"
      method="{$element->getMethod()}"
      enctype="{$element->getAttrib('enctype')}"
      id="{$element->getId()}"
      name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
      {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
      class="form-horizontal">
      
{if isset( $element->salt )}
    {include file='form/element-input.phtml' ielement=$element->salt}
{/if}

{include file='form/element-input.phtml' ielement=$element->username}


	<fieldset class="control-group" id="div-form-{$element->password->getId()}">
	    <label for="{$element->password->getId()}" class="control-label {if isset($alert) && $alert}alert-heading{/if}">
	    	{$element->password->getLabel()}
    	</label>
	    <div id="div-controls-{$element->password->getId()}" class="controls">
		    {$element->password}
		    <span class="btn" onclick="$( '#{$element->password->getId()}' ).val( randomPassword( 12 ) );">Random</span>

        	{if $element->password->getMessages()}
				<script type="text/javascript">
					$( '#{$element->password->getId()}' ).addClass( 'error' );
					$( '#div-form-{$element->password->getId()}' ).addClass( 'error' );
				</script>
				<p id="help-{$element->password->getId()}" class="help-block">
					{foreach from=$element->password->getMessages() item=messages}
    					{foreach from=$messages item=msg}
        					{$msg}<br />
    					{/foreach}
					{/foreach}
				</p>
			{/if}
	    </div>
	</fieldset>

        
{if isset( $element->active )}
    {include file='form/element-input.phtml' ielement=$element->active}
{/if}
{if isset( $element->super )}
    {include file='form/element-input.phtml' ielement=$element->super}
{/if}
{if isset( $element->welcome_email )}
    {include file='form/element-input.phtml' ielement=$element->welcome_email}
{/if}

<fieldset class="form-actions">
    {if $controller eq 'auth' and $action eq 'setup'}
        <input type="submit" class="btn btn-success" value="Activate My Account &raquo;" />
    {else}
        <span class="btn btn-danger" onclick="parent.$.fn.colorbox.close();">{$element->cancel->getLabel()}</span>
        &nbsp;
        <input class="btn btn-success" type="submit" id="{$element->save->getId()}" value="{$element->save->getLabel()}" />
        &nbsp; &nbsp;
        <span id="saving" class="hide">
            <img src="{genUrl}/images/throbber.gif" alt="Processing..." title="Processing..." />
            Processing...
        </span>
    {/if}
</fieldset>


</form>

</div> <!-- #form_div_edit_mailbox -->
