<div id="form_div_admin_password">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

        {include file='form/element-input.phtml' ielement=$element->password}
        {if isset($element->email)}
            {include file='form/element-checkbox.phtml' ielement=$element->email}
        {/if}

        {if !isset( $modal) || !$modal}
        <fieldset class="form-actions">
            <input clas="btn btn-primary" type="submit" value="{$element->change->getLabel()}" />
        </fieldset>
        {/if}

</div> <!-- #form_div_admin_password -->
