<div id="form_div_admin_password">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="default_form">

        <table>
            <tr>
                <td class="right bold valign_top">{$element->password->getLabel()}</td>
                <td>
                    {$element->password}
                    {include file='form_element_errors.phtml' pTheElement=$element->password}
                </td>
            </tr>
        {if isset($element->email)}
            <tr>
                <td class="right bold"><label for="{$element->email->getId()}" class="inline">{$element->email->getLabel()}</label></td>
                <td>{$element->email}</td>
            </tr>
        {/if}
            <tr>
                <td></td>
                <td>
                    <br />
                    <input type="submit" value="{$element->change->getLabel()}" />
                </td>
            </tr>
        </table>
    </form>

</div> <!-- #form_div_admin_password -->
