<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * AdminPreference
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminPreference extends EntityRepository
{
}
