<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * AliasPreference
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasPreference extends EntityRepository
{
}
