<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Archive
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Archive extends EntityRepository
{
    /**
     * Load archives for archive list .
     *
     * If admin is super he gets all mailboxes.
     *
     * @param \Entities\Admin $admin Admin for filtering mailboxes.
     * @param \Entities\Domain $domain Domain for filtering mailboxes.
     * @return array
     */
    public function loadForArchiveList( $admin, $domain = null )
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select( 'a.id as id , a.username as username, a.status as status, d.domain as domain' )
            ->from( '\\Entities\\Archive', 'a' )
            ->join( 'a.Domain', 'd' );

        if( !$admin->isSuper() )
            $qb->join( 'd.Admins', 'd2a' )
                ->where( 'd2a = :admin' )
                ->setParameter( 'admin', $admin );

        if( $domain )
            $qb->andWhere( 'a.Domain = ?2' )
                ->setParameter( 2, $domain );

        return $qb->getQuery()->getArrayResult();
    }
}
