<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * DatabaseVersion
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseVersion extends EntityRepository
{
}
