<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * DomainPreference
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainPreference extends EntityRepository
{
}
