<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Log
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Log extends EntityRepository
{
	/**
     * Load logs for log list .
     *
     * @param \Entities\Admin $admin Admin for filtering mailboxes.
     * @param \Entities\Domain $domain Domain for filtering mailboxes.
     * @return array
     */
    public function loadForLogList( $admin, $domain = null )
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select( 'l.id as id , l.action as action, l.data as data, l.timestamp as timestamp, a.username as admin, d.domain as domain' )
            ->from( '\\Entities\\Log', 'l' )
            ->leftJoin( 'l.Domain', 'd' )
            ->join( 'l.Admin', 'a' );
        
        if( $admin )
            $qb->join( 'd.Admins', 'd2a' )
                ->where( 'd2a = ?1' )
                ->setParameter( 1, $admin );

        if( $domain )
            $qb->andWhere( 'l.Domain = ?2' )
                ->setParameter( 2, $domain );

        return $qb->getQuery()->getArrayResult();  
    }
}
