{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >

        {if $user->isSuper()}
        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn" id="asign_domain have-tooltip" href="{genUrl controller='admin' action='assign-domain' aid=$targetAdmin->getId()}" title="Assign Domain" >
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>
    	</div>
    	{/if}

        <h1>Domains<small> for {$targetAdmin->getUsername()}</small></h1>
    </div>

    {OSS_Message}


<table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Domain</th>
            <th width="30"></th>
        </tr>
    </thead>
    <tbody>
    {foreach $targetAdmin->getDomains() as $domain}
        <tr id="domain_{$domain->getId()}">
            <td>{$domain->getDomain()}{if !$domain->getActive()} (inactive){/if}</td>
            <td>
                <a class="btn btn-small have-tooltip-below" id="remove-domain-{$domain->getId()}" href="{genUrl controller='admin' action='remove-domain' aid=$targetAdmin->getId() did=$domain->getId()}" ref="{$domain->getDomain()}" title="Remove">
                    <i class="icon-minus"></i>
                </a>
            </td>
        </tr>
    {/foreach}
    </tbody>
</table>
<br/>
<br/>

<div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to remove <em id="purge_admin_name">{$targetAdmin->getUsername()}</em> from <em id="purge_domain_name"></em> ?
    </div>
    <div id="pdfooter" class="modal-footer">
        <a class="btn btn-danger" id="purge_dialog_delete" href="#">Remove</a>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

<script type="text/javascript">{tmplinclude file='admin/js/domains.js'}</script>
</div>
{tmplinclude file="footer.phtml"}
