{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn have-tooltip-below" id="add_admin"  title="Add Administrator" href="{genUrl controller='admin' action='add'}">
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>
    	</div>

        <h1>Administrators</h1>
    </div>

{OSS_Message}

<table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Username</th>
            <th width="55">Active</th>
            <th width="55">Super</th>
            <th width="115"></th>
        </tr>
    </thead>
    <tbody>
        {foreach $admins as $admin}
            <tr id="admin_{$admin->getId()}">
                <td>{$admin->getUsername()}</td>
                <td>
                    <div id="throb-toggle-active-{$admin->getId()}" style="float: right;"></div>
                    {if $identity.user->getId() != $admin->getId()}
                        <span id="toggle-active-{$admin->getId()}" onclick="toggleActive( 'toggle-active-{$admin->getId()}', {$admin->getId()} );" class="btn btn-mini {if $admin->getActive()}btn-success{else}btn-danger{/if}">{$admin->getActive()|yesno}</span>
                    {else}
                        <span id="toggle-active-{$admin->getId()}" class="btn btn-mini disabled {if $admin->getActive()}btn-success{else}btn-danger{/if}">{$admin->getActive()|yesno}</span>
                    {/if}
                </td>
                <td>
                    <div id="throb-toggle-super-{$admin->getId()}" style="float: right;"></div>
                    {if $identity.user->getId() != $admin->getId()}
                        <span id="toggle-super-{$admin->getId()}" onclick="toggleSuper( 'toggle-super-{$admin->getId()}', {$admin->getId()} );" class="btn btn-mini {if $admin->getSuper()}btn-success{else}btn-danger{/if}">{$admin->getSuper()|yesno}</span>
                    {else}
                        <span id="toggle-super-{$admin->getId()}" class="btn btn-mini disabled {if $admin->getSuper()}btn-success{else}btn-danger{/if}">{$admin->getSuper()|yesno}</span>
                    {/if}
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-mini have-tooltip" id="password-{$admin->getId()}" title="Password" href="{genUrl controller='admin' action='password' aid=$admin->getId()}">
                            <i class="icon-lock"></i>
                        </a>
                        <a class="btn btn-mini have-tooltip" id="admin_logs_{$admin->getId()}" title="Logs" href="{genUrl controller='log' action='list' aid=$admin->getId()}">
                            <i class="icon-align-justify"></i>
                        </a>

                        {if $identity.user->getId() != $admin->getId() }
                            <a class="btn btn-mini have-tooltip {if $admin->isSuper()}hide{/if}" id="admin_domains_{$admin->getId()}" title="List Domains" href="{genUrl controller='admin' action='domains' aid=$admin->getId()}">
                                <i class="icon-screenshot"></i>
                            </a>
                            <a class="btn btn-mini have-tooltip" id="purge-admin-{$admin->getId()}" title="Purge"  href="{genUrl controller='admin' action='purge' aid=$admin->getId()}" ref="{$admin->getUsername()}">
                                <i class="icon-trash"></i>
                            </a>
                        {/if}

                    </div>
                </td>
            </tr>
        {/foreach}
    </tbody>
</table>


<div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to purge <em id="purge_admin_name"></em> ?
        <br /><br />
        All logs and domain associations will be removed. If you simply want to
        close the user's account, deactivate it instead.
        <br /><br />
    </div>
    <div id="pdfooter" class="modal-footer">
        <a class="btn btn-danger" id="purge_dialog_delete" href="#">Purge</a>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

<script type="text/javascript">{tmplinclude file='admin/js/list.js'}</script>
<br />
</div>
{tmplinclude file="footer.phtml"}
