{include file="header.phtml"}

{assign var='changePwdParams' value="open: true, iframe: true, transition: 'elastic', width: '700px', height: '270px'"}
{assign var='addAdminParams' value="open: true, iframe: true, transition: 'elastic', width: '500px', height: '400px'"}
{assign var='domainListParams' value="open: true, iframe: true, transition: 'elastic', width: '700px', height: '600px'"}

<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn" id="modal-dialog-add_admin" href="{genUrl controller='admin' action='add' modal=true}" title="Add Admin">
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>
    	</div>

        <h1>Administrators</h1>
    </div>

{ViMbAdmin_Messages}

<table id="admin_list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Username</th>
            <th>Active</th>
            <th>Super</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
{foreach $admins as $oneAdmin}
    <tr id="admin_{$oneAdmin.id}" {if $identity.admin.id == $oneAdmin.id}class="bold"{/if}>
        <td>{$oneAdmin.username}</td>
        <td>
            <div id="throb-toggle-active-{$oneAdmin.id}" style="float: right;"></div>
            {if $identity.admin.id != $oneAdmin.id}
                <span id="toggle-active-{$oneAdmin.id}" onclick="toggleActive( 'toggle-active-{$oneAdmin.id}', {$oneAdmin.id} );" class="btn btn-mini {if $oneAdmin.active}btn-success{else}btn-danger{/if}">{$oneAdmin.active|yesno}</span>
            {else}
                <span id="toggle-active-{$oneAdmin.id}" class="btn btn-mini disabled {if $oneAdmin.active}btn-success{else}btn-danger{/if}">{$oneAdmin.active|yesno}</span>
            {/if}
        </td>
        <td>
            <div id="throb-toggle-super-{$oneAdmin.id}" style="float: right;"></div>
            {if $identity.admin.id != $oneAdmin.id}
                <span id="toggle-super-{$oneAdmin.id}" onclick="toggleSuper( 'toggle-super-{$oneAdmin.id}', {$oneAdmin.id} );" class="btn btn-mini {if $oneAdmin.super}btn-success{else}btn-danger{/if}">{$oneAdmin.super|yesno}</span>
            {else}
                <span id="toggle-super-{$oneAdmin.id}" class="btn btn-mini disabled {if $oneAdmin.super}btn-success{else}btn-danger{/if}">{$oneAdmin.super|yesno}</span>
            {/if}
        </td>
        <td>
            <a class="btn btn-mini" id="modal-dialog-password-{$oneAdmin.id}" href="{genUrl controller='admin' action='password' modal=true aid=$oneAdmin.id}">Password</a>
            <a class="btn btn-mini" href="{genUrl controller='log' action='list'}/aid/{$oneAdmin.id}">Log</a>
            {if not $oneAdmin.super}
                <a class="btn btn-mini" href="{genUrl controller='admin' action='domains'}/aid/{$oneAdmin.id}">Domains</a>
            {/if}
            {if $identity.admin.id neq $oneAdmin.id}
                <span class="btn btn-mini" id="purge-admin-{$oneAdmin.id}"  onclick="purgeAdmin( {$oneAdmin.id}, '{$oneAdmin.username}' );">Purge</span>
            {/if}
        </td>
    </tr>
{/foreach}
    </tbody>
</table>


<div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to purge <em id="purge_admin_name"></em> ?
        <br /><br />
        All logs and domain associations will be removed. If you simply want to
        close the user's account, deactivate it instead.
        <br /><br />
    </div>
    <div id="pdfooter" class="modal-footer">
        <span class="btn btn-danger" id="purge_dialog_delete">Purge</span>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

{include file='admin/js/list.js'}
<br />
</div>
{include file="footer.phtml"}
