{if !isset( $modal) || !$modal }
    {include file="header.phtml"}
    <div class="page-content" >
        <div class="page-header" >
            <h1>New Password {if isset( $targetAdmin ) and $targetAdmin.id != $identity.admin.id}for {$targetAdmin.username}{/if}</h1>
        </div>
        {ViMbAdmin_Messages}
{else}
<div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
            <h3>New Password {if isset( $targetAdmin ) and $targetAdmin.id != $identity.admin.id}for {$targetAdmin.username}{/if}</h3>
    </div>
    <div class="modal-body">
{/if}

{$form}

{addJSValidator form=$form}

{if !isset( $modal) || !$modal }
    </div>
    {include file="footer.phtml"}
{else}
    </div>
    <div class="modal-footer" id="mtfooter">
        <button id="modal_dialog_save" class="btn btn-primary">Save</button>
        <button id="modal_dialog_cancel" class="btn">Cancel</button>
        <script type="text/javascript">
    $(document).ready(function()
    {
        $('#modal_dialog_save').bind('click', function() {
            var data = $('#modal_dialog').html();

            var Throb = tt_throbber( 32, 14, 1.8 ).appendTo( $( '#mtfooter' ).get(0) ).start();

            $('#modal_dialog_save').attr('disabled', 'disabled' ).addClass( 'disabled' );
            $('#modal_dialog_cancel').attr('disabled', 'disabled' ).addClass( 'disabled' );

            $.ajax({
                url: "{genUrl controller='admin' action='password' aid=$targetAdmin.id}",
                data: $( '#change_password_form' ).serialize()+"&helper=0",
                async: true,
                cache: false,
                type: 'POST',
                timeout: 10000,
                success: function(data) {
                    if( data.substring( 0, 2)  == "ok" ) {
                        data = data.split( "_" );

                        if( data[1] == "user" )
                            ossAddMessage( 'You have successfully changed the user\'s password.', 'success' );
                        else
                            ossAddMessage( 'You have successfully changed your password.', 'success' );

                        dialog.modal('hide');
                    }
                    else if( data.substring( 0, 5)  == "error" ) {
                        data = data.split( "_" );

                        if( data[1] == "inpr" )
                            ossAddMessage( 'You have insufficient privileges for this task.', 'error' );
                        else if( data[1] == "none" )
                            ossAddMessage( 'Invalid or non-existent admin.', 'error' );
                        else
                            ossAddMessage( 'Sending the change password email failed.', 'info' );

                            dialog.modal('hide');
                    }
                    else if( data.substring(0, 26) == '<div class="modal-header">' ){
                        $('#modal_dialog').html( data );
                        $( '#modal_dialog_cancel' ).bind( 'click', function(){
                            dialog.modal('hide');
                        });

                        $( '#domain' ).bind( 'change', function() { ossJscriptFieldValidator( 'domain' ) } );
                    }
                    else {
                        dialog.modal('hide');
                        ossAddMessage( 'An unexpected error has occured.', 'error' );
                    }
                },
                error:   ossAjaxErrorHandler
            });
        });
    });
    </script>
    </div>

{/if}
