{if !isset( $modal) || !$modal }
    {include file="header.phtml"}
    <div class="page-content" >
        <div class="page-header" >
            <h1>{$operation} Domain: {$domainModel.domain}</h1>
        </div>
        {ViMbAdmin_Messages}
{else}
<div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
            <h3>{$operation} Domain: {$domainModel.domain}</h3>
    </div>
    <div class="modal-body" style="min-height: 200px;">
{/if}

{$editForm}

{addJSValidator form=$editForm}

{if !isset( $modal) || !$modal }
    </div>
    {include file="footer.phtml"}
{else}
    </div>
    <div class="modal-footer" id="mtfooter">
        <button id="modal_dialog_save" class="btn btn-primary">{if $operation == 'Add'}Add{else}Save{/if}</button>
        <button id="modal_dialog_cancel" class="btn">Cancel</button>
        <span class="btn" id="toogle_advanced">Advanced</span>
        <script type="text/javascript">
    $(document).ready(function()
    {
        $('#modal_dialog_save').bind('click', function() {
            valid = true;
            var data = $('#modal_dialog').html();

            var Throb = tt_throbber( 32, 14, 1.8 ).appendTo( $( '#mtfooter' ).get(0) ).start();

            $('#modal_dialog_save').attr('disabled', 'disabled' ).addClass( 'disabled' );
            $('#modal_dialog_cancel').attr('disabled', 'disabled' ).addClass( 'disabled' );

            $.ajax({
                url: "{genUrl controller='domain' action='edit' did=$domainModel.id}",
                data: $( '#domain_edit_form' ).serialize()+"&helper=0",
                async: true,
                cache: false,
                type: 'POST',
                timeout: 10000,
                success: function(data) {
                    if( data == "ok" ) {
                        dialog.modal('hide');
                            location.reload();
                    }
                     else if( data.substring(0, 26) == '<div class="modal-header">' ) {
                                $('#modal_dialog').html( data );
                                $( '#modal_dialog_cancel' ).bind( 'click', function(){
                                    dialog.modal('hide');
                                });

                                $( '#domain' ).bind( 'change', function() { ossJscriptFieldValidator( 'domain' ) } );
                    }
                    else {
                        dialog.modal('hide');
                        ossAddMessage( 'An unexpected error has occured.', 'error' );
                    }
                },
                error:   ossAjaxErrorHandler
            });
        });
    });
    </script>
    </div>

{/if}
