{include file="header.phtml"}

{assign var='addDomainParams' value="open: true, iframe: true, transition: 'elastic', width: '800px', height: '480px'"}

<div class="page-content" >

    <div class="page-header" >

        {if $identity.admin.super}
        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	    <a class="btn" id="modal-dialog-wide_add_domain" title="Add Domain" href="{genUrl controller='domain' action='edit' modal=1}" >
            	        <i class="icon-plus"></i>
        	    </a>
            	</span>
            	<script>
                    $( document ).ready( function(){
                        $( '#modal-dialog-wide_add_domain' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover', placement: 'bottom' } );
                    });
                </script>
            </div>
    	</div>
    	{/if}

        <h1>Domains</h1>
    </div>

    {ViMbAdmin_Messages}

<table id="domain_list_table"  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Domain</th>
            <th>Mailboxes</th>
            <th>Aliases</th>
            <th width="55">Active</th>
            <th>Transport</th>
            <th>Backup MX</th>
            <th>Created</th>
            <th width="115"></th>
        </tr>
    </thead>
    <tbody>
        {foreach $domains as $oneDomain}
            <tr id="domain_{$oneDomain.id}">
                <td>{$oneDomain.domain}</td>
                <td>
                    <a class="btn btn-mini" id="modal-dialog-add_mailbox_{$oneDomain.id}" title="Add Mailbox" href="{genUrl controller='mailbox' action='edit' did=$oneDomain.id modal=1}"><i class="icon-plus"></i></a>&nbsp;&nbsp;
                    <a class="ul" href="{genUrl controller='mailbox' action='list' did=$oneDomain.id}">{$oneDomain->countMailboxes()}{if $oneDomain.mailboxes}/{$oneDomain.mailboxes}{/if}</a>
                </td>
                <td>
                    <a class="btn btn-mini" id="modal-dialog-add_alias_{$oneDomain.id}" title="Add Alias" href="{genUrl controller='alias' action='edit' did=$oneDomain.id modal=1}"><i class="icon-plus"></i></a>&nbsp;&nbsp;
                    <a class="ul" href="{genUrl controller='alias' action='list' did=$oneDomain.id}">{$oneDomain->countAliases( true )}{if $oneDomain.aliases}/{$oneDomain.aliases}{/if}</a>
                </td>
                <td>
                    <div id="throb-toggle-active-{$oneDomain.id}" style="float: right;"></div>
                    <span id="toggle-active-{$oneDomain.id}" onclick="toggleActive( 'toggle-active-{$oneDomain.id}', {$oneDomain.id} );" class="btn btn-mini {if $oneDomain.active}btn-success{else}btn-danger{/if}">{$oneDomain.active|yesno}</span>
                </td>
                <td>{$oneDomain.transport}</td>
                <td>{$oneDomain.backupmx|yesno}</td>
                <td>{$oneDomain.created}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-mini" id="modal-dialog-wide_edit_domain_{$oneDomain.id}" title="Edit" href="{genUrl controller='domain' action='edit' did=$oneDomain.id modal=true}">
                            <i class="icon-pencil"></i>
                        </a>
                        {if $identity.admin.super}
                            <a class="btn btn-mini" id="domain_admins_{$oneDomain.id}" title="List Admins" href="{genUrl controller='domain' action='admins' did=$oneDomain.id}">
                                <i class="icon-user"></i>
                            </a>
                        {/if}
                        <a class="btn btn-mini" id="domain_logs_{$oneDomain.id}" title="Logs" href="{genUrl controller='log' action='list' did=$oneDomain.id}">
                            <i class="icon-align-justify"></i>
                        </a>
                        {if $identity.admin.super}
                            <span  class="btn btn-mini"  id="purge-domain-{$oneDomain.id}" title="Purge" onclick="purgeDomain({$oneDomain.id}, '{$oneDomain.domain}');">
                                <i class="icon-trash"></i>
                            </span>
                        {/if}
                    </div>
                    <script>
                        $( document ).ready( function(){
                            $( '#modal-dialog-wide_edit_domain_{$oneDomain.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                            $( '#domain_admins_{$oneDomain.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                            $( '#domain_logs_{$oneDomain.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                            $( '#purge-domain-{$oneDomain.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                            $( '#modal-dialog-add_mailbox_{$oneDomain.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                            $( '#modal-dialog-add_alias_{$oneDomain.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                        });
                    </script>
                </td>
            </tr>
        {/foreach}
    </tbody>
</table>


{include file='domain/js/list.js'}

<div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to purge
        <em id="purge_domain_name"></em> ?
        <br>
        <br>
        All mailboxes, aliases and logs will be removed.
        <br>
        <br>
    </div>
    <div id="pdfooter" class="modal-footer">
        <span class="btn btn-danger" id="purge_dialog_delete">Purge</span>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

</div>

{include file="footer.phtml"}
