{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >

        {if $user->isSuper()}
        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	    <a class="btn have-tooltip-below" id="add_domain" title="Add Domain" href="{genUrl controller='domain' action='add'}" >
            	        <i class="icon-plus"></i>
        	    </a>
            	</span>
            </div>
    	</div>
    	{/if}

        <h1>Domains</h1>
    </div>

    {OSS_Message}

<table id="list_table"  cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Domain</th>
            <th>Mailboxes</th>
            <th>Aliases</th>
            {if isset($options.defaults.list_size.disabled) && !$options.defaults.list_size.disabled}
                <th>Size ({$size_multiplier})</th>
            {/if}
            <th width="55">Active</th>
            <th>Transport</th>
            <th>Backup MX</th>
            <th>Created</th>
            <th width="115"></th>
        </tr>
    </thead>
    <tbody>
        {foreach $domains as $domain}
            <tr id="domain_{$domain.id}">
                <td>{$domain.name}</td>
                <td>
                    <a class="btn btn-mini have-tooltip" id="add_mailbox_{$domain.id}" title="Add Mailbox" href="{genUrl controller='mailbox' action='add' did=$domain.id}"><i class="icon-plus"></i></a>&nbsp;&nbsp;
                    <a class="ul" href="{genUrl controller='mailbox' action='list' did=$domain.id}">{$domain.mailboxes}{if $domain.maxmailboxes}/{$domain.maxmailboxes}{/if}</a>
                </td>
                <td>
                    <a class="btn btn-mini have-tooltip" id="add_alias_{$domain.id}" title="Add Alias" href="{genUrl controller='alias' action='add' did=$domain.id}"><i class="icon-plus"></i></a>&nbsp;&nbsp;
                    <a class="ul" href="{genUrl controller='alias' action='list' did=$domain.id}">{$domain.aliases}{if $domain.maxaliases}/{$domain.maxaliases}{/if}</a>
                </td>
                {if isset($options.defaults.list_size.disabled) && !$options.defaults.list_size.disabled}
                    <td>
                        {if $domain.mailboxes_size}
                            {($domain.mailboxes_size/$multiplier)|string_format:"%.3f"}
                        {else}
                            0
                        {/if}
                    </td>
                {/if}
                <td>
                    <div id="throb-toggle-active-{$domain.id}" style="float: right;"></div>
                    <span id="toggle-active-{$domain.id}" onclick="toggleActive( 'toggle-active-{$domain.id}', {$domain.id}, '.', '' );" class="btn btn-mini {if $domain.active}btn-success{else}btn-danger{/if}">{$domain.active|yesno}</span>
                </td>
                <td>{$domain.transport}</td>
                <td>{$domain.backupmx|yesno}</td>
                <td>{$domain.created->format( 'Y-m-d' )}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-mini have-tooltip" id="edit_domain_{$domain.id}" title="Edit" href="{genUrl controller='domain' action='edit' did=$domain.id}">
                            <i class="icon-pencil"></i>
                        </a>
                        {if isset( $domain_actions ) }
                            {assign var=oid value=$mbox.id}
                            {foreach $domain_actions as $action}
                                {if isset( $action.menu ) }
                                    {assign var="action_list_menu" value=$action}
                                {else}
                                    <{$action.tagName} {foreach $action as $attrib => $value}{if !in_array( $attrib, [ "tagName", "child"] )}{$attrib}="{$value|replace:'%id%':$oid}" {/if}{/foreach}>
                                    {if !is_array( $action.child ) }
                                        {$action.child}
                                    {else}
                                        <{$action.child.tagName} {foreach $action.child as $attrib => $value}{if $attrib != "tagName"}{$attrib}="{$value}" {/if}{/foreach} {if $action.child.tagName != "img"}></{$action.child.tagName}>{else}/>{/if}
                                    {/if}
                                    </{$action.tagName}>
                                {/if}
                            {/foreach}
                        {/if}
                        {if $user->isSuper()}
                            <a class="btn btn-mini have-tooltip" id="domain_admins_{$domain.id}" title="Administrators" href="{genUrl controller='domain' action='admins' did=$domain.id}">
                                <i class="icon-user"></i>
                            </a>
                        {/if}
                        <a class="btn btn-mini have-tooltip" id="domain_logs_{$domain.id}" title="Logs" href="{genUrl controller='log' action='list' did=$domain.id}">
                            <i class="icon-align-justify"></i>
                        </a>
                        {if $user->isSuper()}
                            <span  class="btn btn-mini have-tooltip"  id="purge-domain-{$domain.id}" title="Purge" onclick="purgeDomain({$domain.id}, '{$domain.name}');">
                                <i class="icon-trash"></i>
                            </span>
                        {/if}
                        {if isset( $action_list_menu)}
                        {assign var="action" value=$action_list_menu}
                        <{$action.tagName} {foreach $action as $attrib => $value}{if !in_array( $attrib, [ "tagName", "child", "menu" ] )}{$attrib}="{$value|replace:'%id%':$oid}" {/if}{/foreach}>
                        {if !is_array( $action.child ) }
                            {$action.child}
                        {else}
                            <{$action.child.tagName} {foreach $action.child as $attrib => $value}{if $attrib != "tagName"}{$attrib}="{$value}" {/if}{/foreach} {if $action.child.tagName != "img"}></{$action.child.tagName}>{else}/>{/if}
                        {/if}
                        <span class="caret"></span>
                        </{$action.tagName}>
                        <ul class="dropdown-menu pull-right">
                        {foreach $action.menu as $item}
                            <li><a {if isset( $item.id)}id="{$item.id|replace:'%id%':$oid}" {/if}href="{$item.url|replace:'%id%':$oid}">{$item.text}</a></li>
                        {/foreach}
                        </ul>
                    {/if}
                    </div>
                </td>
            </tr>
        {/foreach}
    </tbody>
</table>

<script>{tmplinclude file='domain/js/list.js'}</script>

<div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to purge
        <em id="purge_domain_name"></em> ?
        <br>
        <br>
        All mailboxes, aliases and logs will be removed.
        <br>
        <br>
    </div>
    <div id="pdfooter" class="modal-footer">
        <a class="btn btn-danger" id="purge_dialog_delete" href="">Purge</a>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

</div>

{tmplinclude file="footer.phtml"}
