{tmplinclude file="header.phtml"}

{if isset( $session->domain ) && $session->domain }
    {assign var=domain value=$session->domain}
{/if}

<div class="page-content" >

    <div class="page-header" >
        <h1>
            Logs{if isset( $domain ) && $domain }<small> for {$domain->getDomain()}</small>
                <a class="btn have-tooltip-below" id="show_all_logs" title="Show All" href="{genUrl controller='log' action='list' unset=1}">
                    <i class="icon-remove-circle"></i>
                </a>
            {/if}
        </h1>
    </div>


{OSS_Message}

<table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Action</th>
            <th>Log</th>
            <th>Admin</th>
            {if !isset( $domain ) || !$domain }
                <th>Domain</th>
            {/if}
            <th>Occurred At</th>
        </tr>
    </thead>
    <tbody>
{foreach $logs as $log}
        <tr>
            <td>{$log.action}</td>
            <td>
                {*
                    <div id="log-message-{$log.id}" {if strlen( $log.data ) > 40 } title="{$log.data|regex_replace:"/[\r\t\n]/":" "}" class="have-tooltip-long"{/if}>
                        {$log.data|shorten:40}
                    </div>
                *}
                    {$log.data}
            </td>
            <td>{$log.admin}</td>
            {if !isset( $domain ) || !$domain }
                <td>{$log.domain}</td>
            {/if}
            <td>{$log.timestamp->format( "Y-m-d H:i:s" )}</td>
        </tr>
{/foreach}
    </tbody>
</table>

<br />
<br />

<script type="text/javascript">{tmplinclude file='log/js/list.js'}</script>
</div>
{tmplinclude file="footer.phtml"}
