{include file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>
            Logs{if isset( $session->domain ) && $session->domain }<small> for {$session->domain.domain}</small>{/if}
            {if isset( $session->domain ) && $session->domain}
                <a class="btn" title="Show All" href="{genUrl controller='log' action='list' unset=1}"><i class="icon-remove-circle"></i></a>
            {/if}
        </h1>
    </div>


{ViMbAdmin_Messages}

<table id="log_list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Action</th>
            <th>Data</th>
            <th>Admin</th>
            <th>Domain</th>
            <th>Created</th>
        </tr>
    </thead>
    <tbody>
{foreach $logEntries as $oneLog}
        <tr>
            <td>{$oneLog.action}</td>
            <td id="log-message-{$oneLog.id}">
                {$oneLog.data|shorten:40}
                {if strlen( $oneLog.data ) > 40 }
                    <script type="text/javascript">
                        $( document ).ready( function(){
                            $( "#log-message-{$oneLog.id}" ).tooltip({ trigger: 'hover', delay: { show: 2000, hide: 100 }, title: '{$oneLog.data|regex_replace:"/[\r\n]/":" "}' });
                        });
                    </script>
                {/if}
            </td>
            <td>{$oneLog.Admin.username}</td>
            <td>{$oneLog.Domain.domain}</td>
            <td>{$oneLog.timestamp}</td>
        </tr>
{/foreach}
    </tbody>
</table>

<br />
<br />

{include file='log/js/list.js'}
</div>
{include file="footer.phtml"}
