<div class="tab-pane fade" id="tab_plugsf_accessPermissions">
    {include file='form/element-checkbox.phtml' ielement=$element->plugin_accessPermissions}
    <div id="divAccessPermissions" class="row-fluid dontdisplay">
        <div class="span8 offset2">
        	    
            <p>
                Deselecting <em>{$element->plugin_accessPermissions->getLabel()}</em> above will remove specific
                access permissions and restore default behavior (access all).
            </p>
        	    
            <fieldset>
        	    <legend>Access Permissions</legend>

        	    {foreach $element->getAccessElements() as $e}
        	        {include file='form/element-checkbox.phtml' ielement=$element->$e}
        	    {/foreach}
            </fieldset>
        </div>
    </div>

    <script type="text/javascript">
    
    addPluginTab( 'Access', 'tab_plugsf_accessPermissions' );
    $(document).ready(function()
    {
        if( $( "#plugin_accessPermissions" ).attr( "checked" ) == "checked" )
        {
            $( "#divAccessPermissions" ).show();
        }


        $( "#plugin_accessPermissions" ).change( function(){
            $( "#divAccessPermissions" ).slideToggle( "slow" );
        });
    });
    
    </script>
</div>
