<div id="form_div_change_mailbox_pwd">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

        {include file='form/element-input.phtml' ielement=$element->username}
        {include file='form/element-input.phtml' ielement=$element->current_password}
        {include file='form/element-input.phtml' ielement=$element->new_password}
        {include file='form/element-input.phtml' ielement=$element->confirm_new_password}

        <fieldset class="form-actions">
            <a class="btn" href="{genUrl controller='auth' action='login'}" >Cancel</a>
            &nbsp;
            <input class="btn btn-primary" type="submit" id="{$element->change->getId()}" value="{$element->change->getLabel()}" />
        </fieldset>
    </form>

</div> <!-- #form_div_edit_mailbox -->
