<div id="form_div_change_mailbox_pwd">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="default_form">

        <table>
            <tr>
                <td class="right bold valign_top">{$element->username->getLabel()}</td>
                <td>
                    {$element->username}
                    {include file='form_element_errors.phtml' pTheElement=$element->username}
                </td>
            </tr>
            <tr>
                <td class="right bold valign_top">{$element->current_password->getLabel()}</td>
                <td>
                    {$element->current_password}
                    {include file='form_element_errors.phtml' pTheElement=$element->current_password}
                </td>
            </tr>
            <tr>
                <td class="right bold valign_top">{$element->new_password->getLabel()}</td>
                <td>
                    {$element->new_password}
                    {include file='form_element_errors.phtml' pTheElement=$element->new_password}
                </td>
            </tr>
            <tr>
                <td class="right bold valign_top">{$element->confirm_new_password->getLabel()}</td>
                <td>
                    {$element->confirm_new_password}
                    {include file='form_element_errors.phtml' pTheElement=$element->confirm_new_password}
                </td>
            </tr>
        </table>

        <input type="button" onclick="document.location.href='{genUrl controller='auth' action='login'}';" value="Cancel" />
        &nbsp;
        <input type="submit" id="{$element->change->getId()}" value="{$element->change->getLabel()}" />
    </form>

</div> <!-- #form_div_edit_mailbox -->
