<div id="form_div_edit_mailbox">

    <form action="{$element->getAction()}"
          method="{$element->getMethod()}"
          enctype="{$element->getAttrib('enctype')}"
          id="{$element->getId()}"
          name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
          {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
          class="form-horizontal">

          <fieldset class="control-group" id="div-form-address">
    	    <label for="local_part" class="control-label">
	    	    	Address
	    	</label>
    	    <div id="div-controls-{$element->local_part->getId()}" class="controls">
    		    <div class="input-append" style="float: left;">
    		        {$element->local_part}
    		        {if !isset( $domain ) || !$domain}
    		            <span class="btn" style="margin-left: -5px; -webkit-border-radius: 0 0 0 0; -moz-border-radius: 0 0 0 0; border-radius: 0 0 0 0;">@</span>
		            {else}
		                <span class="add-on" style="margin-left: -5px;">@{$domain->domain}</span>
		                <div style="display: none;">{$element->domain}</div>
		            {/if}
    		    </div>
		        {if !isset( $domain ) || !$domain}
		            {$element->domain}
		        {/if}

	        	{if $element->local_part->getMessages()}
					<script type="text/javascript">
						$( '#{$element->local_part->getId()}' ).addClass( 'error' );
						$( '#div-form-{$element->local_part->getId()}' ).addClass( 'error' );
					</script>
				{/if}
				<p id="help-{$element->local_part->getId()}" class="help-block">
					{if $element->domain->getMessages()}
    					{foreach from=$element->local_part->getMessages() item=messages}
        					{foreach from=$messages item=msg}
            					{$msg}<br />
        					{/foreach}
    					{/foreach}
					{/if}
				</p>
				{if $element->domain->getMessages()}
					<script type="text/javascript">
						$( '#{$element->domain->getId()}' ).addClass( 'error' );
						$( '#div-form-{$element->domain->getId()}' ).addClass( 'error' );
					</script>
				{/if}
				<p id="help-{$element->domain->getId()}" class="help-block">
					{if $element->domain->getMessages()}
    					{foreach from=$element->domain->getMessages() item=messages}
        					{foreach from=$messages item=msg}
            					{$msg}<br />
        					{/foreach}
    					{/foreach}
					{/if}
				</p>
    	    </div>
    	</fieldset>

        {include file='form/element-input.phtml' ielement=$element->name}

        {if isset($element->password)}
            <fieldset class="control-group" id="div-form-password">
    	    <label for="passowrd" class="control-label">
	    	    	{$element->password->getLabel()}
	    	</label>
    	    <div id="div-controls-{$element->password->getId()}" class="controls">
    		    <div class="input-append">
    		        {$element->password}
    		        {if $element->password->getAttrib('disabled') != 'disabled'}
        		        <span id="password_rand" onclick="randPasword( 12, 'password' );" title="Random Password" class="btn add-on" style="margin-left: -5px;">
                            <i class="icon-refresh"></i>
                        </span>
                    {/if}
    		    </div>

	        	{if $element->password->getMessages()}
					<script type="text/javascript">
						$( '#{$element->password->getId()}' ).addClass( 'error' );
						$( '#div-form-{$element->password->getId()}' ).addClass( 'error' );
					</script>
					{/if}
					<p id="help-{$element->password->getId()}" class="help-block">
					{if $element->password->getMessages()}
    					{foreach from=$element->password->getMessages() item=messages}
        					{foreach from=$messages item=msg}
            					{$msg}<br />
        					{/foreach}
    					{/foreach}
    					{/if}
					</p>

    	    </div>
    	</fieldset>
        {/if}

        {include file='form/element-input.phtml' ielement=$element->quota}
        {include file='form/element-checkbox.phtml' ielement=$element->active}
        {if isset( $element->access_restr ) }
            {include file='form/element-checkbox.phtml' ielement=$element->access_restr}
            <div id="access_restriction_div" style="display:none; margin-top: -25px; margin-left: 20px;">
                <fieldset class="control-group">
                    <label class="control-label">&nbsp;</label>
                    <div id="ar_controls" class="controls" style="position: fixed; z-index: 2;">
                        {$element->access_restriction}
                    </div>
                </fieldset>
            </div>
        {/if}

        {if $element->local_part->getValue() == ''}
            {include file='form/element-checkbox.phtml' ielement=$element->welcome_email}
            <div id="div_welcome_email" class="dontdisplay">
                {include file='form/element-input.phtml' ielement=$element->cc_welcome_email}
            </div>
        {/if}

        {if !isset($modal) || !$modal }
        <fieldset class="form-actions">
            <a class="btn" type="button" href="{genUrl controller='mailbox' action='list'}">Cancel</a>
            <input class="btn btn-primary" type="submit" id="{$element->save->getId()}" value="{$element->save->getLabel()}" />
        </field>
        {/if}
    </form>

    <script type="text/javascript">

        $(document).ready(function()
        {
            $( '#domain' ).chosen();
            $( '#access_restriction' ).chosen();

            if( $( "#access_restr" ).attr( "checked" ) == "checked" )
                $( "#access_restriction_div" ).show();

            if( $( '#domain_chzn' ).css( "width" ).length < 5 )
            {
                $( '#domain_chzn' ).css( "width", "150px" );
                $( '#domain_chzn > .chzn-drop' ).css( "width", "148px" );
                $( '#domain_chzn > .chzn-drop .chzn-search > input' ).css( "width", "110px" );
            }

            $('#welcome_email').bind( 'change', function() {
                $('#div_welcome_email').toggle('slow', function(){
                    if( $( "#welcome_email" ).attr( "checked" ) )
                        $( "#ar_controls" ).removeAttr( "style" );
                    else
                        $( "#ar_controls" ).attr( "style", "position: fixed; z-index: 2;" );
                });
            });

            $( "#access_restr" ).change( function(){
                $( "#access_restriction_div" ).toggle( "slow" );
            });
        }); // document onready

    </script>
</div> <!-- #form_div_edit_mailbox -->
