<form action="{$element->getAction()}"
        method="{$element->getMethod()}"
        enctype="{$element->getAttrib('enctype')}"
        id="{$element->getId()}"
        name="{if $element->getName() != ''}{$element->getName()}{else}{$element->getId()}{/if}"
        {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
        class="form-horizontal">

    <div style="position: fixed; z-index: 1;">
    {$element->type}
    </div>
    <div class="control-group">
        <label class="control-label optional">&nbsp;</label>
        <div class="controls">
        </div>
    </div>
    <div id="other_email" {if $element->type->getValue() != 'other'}style="display: none"{/if}>
        {$element->email}
    </div>

</form>

<script type="text/javascript">
    $( document ).ready( function(){
        //$( "#type" ).chosen();
        
        $( "#type" ).on( 'change', function(){
            if( $( "#type" ).val() == "other" )
                $( '#other_email' ).slideDown( "slow" );
            else
                $( '#other_email' ).slideUp( "slow" );
        });
    });
</script>
