<html>
<body>
<p>
To whom it may concern,
</p>

<p>
You received this email because someone recently requested a 
password reset in <a href="{genUrl}">ViMbAdmin</a>.
</p>

<p>
If this was not you, please ignore this email.
</p>

<p>
If you wish to change your password, please click on this link:
</p>

<p>
<a href="{genUrl controller='auth' action='reset-password' username=$user->getUsername() token=$token}">{genUrl controller='auth' action='password-reset'}</a>
</p>

<p>
Thanks and kind regards,
</p>
<p>
{$options.server.email.name}
</p>
</body>
</html>
