
        <fielset id="div-form-{$name}">
            <div class="action">
            	<dl class="inputs-list">
                     {foreach from=$ielements item=ielement}
            		    <dt>
	            			<label>
	            				<input id="{$ielement->getId()}" type="checkbox"
	            					{if $ielement->isChecked()}checked="checked"{/if}
	            					value="{$ielement->getCheckedValue()}" name="{$ielement->getName()}"
            					/>
            					{if isset( $ilabel )}{$ilabel}{else}{$ielement->getLabel()}{/if}
					        </label>
                        </dt>
                    {/foreach}
                </dl>
            </div>
        </fieldset>
