
    	<fieldset class="control-group" id="div-form-{$ielement->getId()}">
    	    <label for="{$ielement->getId()}" class="control-label {if isset($alert) && $alert}alert-heading{/if}">
    	    	{if isset( $ilabel )}
    	    		{$ilabel}
	    		{else}
	    	    	{$ielement->getLabel()}
    	    	{/if}
	    	</label>
    	    <div id="div-controls-{$ielement->getId()}" class="controls">
    		    {$ielement}
    		    {if isset( $ihint )}
        		    <span id="{$ielement->getId()}_hint" rel="popover" class="label"
        		    	data-content="{$ihint}">?</span>
    		    {/if}

	        	{if $ielement->getMessages()}
					<script type="text/javascript">
						$( '#{$ielement->getId()}' ).addClass( 'error' );
						$( '#div-form-{$ielement->getId()}' ).addClass( 'error' );
					</script>
					<p id="help-{$ielement->getId()}" class="help-block">
    					{foreach from=$ielement->getMessages() item=messages}
        					{foreach from=$messages item=msg}
            					{$msg}<br />
        					{/foreach}
    					{/foreach}
					</p>
				{/if}
    	    </div>
    	</fieldset>
