
    	<fieldset class="control-group" id="div-form-{$ielement->getId()}">
    	    <label for="{$ielement->getId()}" class="control-label">
    	    	{if isset( $ilabel )}
    	    		{$ilabel}
	    		{else}
	    	    	{$ielement->getLabel()}
    	    	{/if}
	    	</label>
    	    <div id="div-controls-{$ielement->getId()}" class="controls">
    		    <div class="input-append btn-group">
    		        {$ielement}
    		        <span id="{$ielement->getId()}_date_pick" title="{$ielement->getLabel()} date picker" class="btn add-on" >
                        <i class="icon-calendar"></i>
                    </span>
    		    </div>
    		    {if isset( $ihint )}
        		    <span id="{$ielement->getId()}_hint" rel="popover" class="label"
        		    	data-content="{$ihint}">?</span>
    		    {/if}

	        	{if $ielement->getMessages()}
					<script type="text/javascript">
						$( '#{$ielement->getId()}' ).addClass( 'error' );
						$( '#div-form-{$ielement->getId()}' ).addClass( 'error' );
					</script>
				{/if}
				<p id="help-{$ielement->getId()}" class="help-block">
				    {if $ielement->getMessages()}
    					{foreach from=$ielement->getMessages() item=messages}
        					{foreach from=$messages item=msg}
            					{$msg}<br />
        					{/foreach}
    					{/foreach}
				    {/if}
				</p>
    	    </div>
    	</fieldset>
