<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('mailbox', 'access_restriction', 'enum', '', array(
             'values' => 
             array(
              0 => 'BOTH',
              1 => 'IMAP',
              2 => 'POP3',
             ),
             'default' => 'BOTH',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('mailbox', 'access_restriction');
    }
}