{include file="header.phtml"}
<div class="page-content" >

    <div class="page-header" >
        <h1>About ViMbAdmin <small>Virtual Mailbox Administration</small></h1>
    </div>
    
    {ViMbAdmin_Messages}

<p>
    <strong>ViMbAdmin</strong> (pronounced vim-be-admin and meaning Virtual Mailbox Administration)
    provides a web based virtual mailbox administration system for use with mail transport agents
    such as Postfix, Sendmail and qmail for example. It allows system administrators to add and
    manage domains and to then add, edit and delete mailboxes and aliases for those domains.
</p>

<h3>Features</h3>

<div class="row-fluid">
    <div class="span6">
    
        <p>
        As of version 2.0.0 released March 2012, standard and enhanced features compared to PostfixAdmin include:
        </p>
        
        <ul>
            <li> Super administrator user level with full access; </li>
            <li> Administration user level with access only to assigned domains and their mailboxes and aliases; </li>
            <li> Super admins can create and modify super admins and admins; </li>
            <li> JQuery Datatable throughout for quick in browser searching and pagination; </li>
            <li> Create, modify and purge domains including limiting the number of mailboxes and aliases
                    a non-super admin can create per-domain; </li>
            <li> Activate / deactivate admins, domains, mailboxes and aliases at the click of a button; </li>
            <li> Full logging; </li>
            <li> Facility for end users (mailbox owners) to change their password; </li>
            <li> Single login point for all administrators whether super or not. </li>
        </ul>
    </div>
    <div class="span6">
        <p>
            Additional features include:
        </p>
        
        <ul>
            <li> Very configurable including:
                <ul>
                    <li> set default values for quotas, number of mailboxes and aliases for domain creation; </li>
                    <li> added additional columns to the mailbox schema (including UID, GID, homedir and maildir); </li>
                    <li> templated welcome and settings email for users; </li>
                </ul>
            </li>
            <li> plain, MD5, SHA1, crypt or salted MD5, SHA1 and crypt mailbox password support; </li>
            <li> admin users table is secured with salted SHA1 passwords; </li>
            <li> Forgotten Password / Password Reset function for admins; </li>
        </ul>
    </div>
</div>

<h3>Behind the Site</h3>

<p>
    <strong>ViMbAdmin</strong> has been developed by <strong>Open Solutions</strong> -
    <a href="http://www.opensolutions.ie/">www.opensolutions.ie</a> - a company based in
    Dublin, Ireland specialising in PHP web application development, Linux and UNIX
    system administration and ISP grade networking and we are releasing it under a GPL
    V3 license.
</p>
<p>
    It is written in <a href="http://www.php.net/">PHP</a> using the
    <a href="http://framework.zend.com/">Zend Framework</a> with
    <a href="http://www.doctrine-project.org/">Doctrine ORM</a> and
    <a href="http://www.smarty.net/">Smarty</a>. The frontend is styled with the
    fantastic <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> and made
    functional with <a href="http://www.jquery.com/">JQuery</a>.
</p>

<p>
    Additional components include <a href="http://www.jqueryui.com/">JQuery UI</a>;
    <a href="http://jacklmoore.com/colorbox/">Colorbox</a>;
    <a href="http://datatables.net/">DataTables</a> - easily one of the best JQuery
    plugins every created; <a href="http://harvesthq.github.com/chosen/">Chosen</a>, a
    JQuery plugin that makes long, unwieldy select boxes much more user-friendly; and
    <a href="http://aino.github.com/throbber.js/">Throbber.js</a> a JavaScript Throbber,
    made using canvas and fully configurable with a gif fallback option.
</p>

<h3>Software License</h3>

<p>
    Copyright (c) 2011 - {$smarty.now|date_format:"Y"} Open Source Solutions Limited, Dublin, Ireland
    - <a href="http://www.opensolutions.ie/">www.opensolutions.ie</a>.<br />
    All Rights Reseved.
</p>

<pre>
ViMbAdmin is free software: you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation, either version 3
of the License, or (at your option) any later version.

ViMbAdmin is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
</pre>

<p>
You should have received a copy of the GNU General Public License
along with ViMbAdmin.  If not, see <a href="http://www.gnu.org/licenses/">http://www.gnu.org/licenses/</a>.
</p>

<p>
Open Source Solutions Limited, Lynx House, Old Church Road, Lower Kilmacud Road, Stillorgan, Co Dublin, Ireland.
</p>

</div>

{include file="footer.phtml"}
