{include file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Login to ViMbAdmin</h1>
    </div>

{ViMbAdmin_Messages}


{if isset( $loggedOut ) and $loggedOut}

<div id="vimbadmin-message-999" class="alert alert-success fade in">
    <a class="close" data-dismiss="alert" href="#">×</a>
    There is no admin to assign to this domain.
</div>

{/if}

<div class="row">

    <div class="span6 offset3">

    	<img src="{genUrl}/images/logo_500x159.jpg" />

        <p>
        Welcome to <em>ViMbAdmin</em>, a web application for managing your virtual mailboxes, domains and aliases.
        </p>

        {$loginForm}


        <div class="well">

            <p>
                Are you a user (mailbox owner) looking to change your <br />
                password? If so, please click on this button:

                <a style="float: right;" class="btn btn-primary" href="{genUrl}/change-password">Mailbox Password Change</a>
            </p>

        </div>


    </div>
</div>

</div>

{include file="footer.phtml"}
