{include file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Password Reset</h1>
    </div>


    {ViMbAdmin_Messages}


    <div class="row">

        <div class="span6 offset3">

        	<img src="{genUrl}/images/logo_500x159.jpg" />

            {$resetForm}

            {addJSValidator form=$resetForm}

            <div class="well">

                <p>
                    Are you a user (mailbox owner) looking to change your <br />
                    password? If so, please click on this button:

                    <a style="float: right;" class="btn btn-primary" href="{genUrl}/change-password">Mailbox Password Change</a>
                </p>

            </div>


        </div>
    </div>

</div>
{include file="footer.phtml"}
