{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Reset Password</h1>
    </div>


    {OSS_Message}


    <div class="row">

        <div class="span6 offset3">

        	<img src="{genUrl}/images/logo_500x159.jpg" />

            {$form}

            {addJSValidator form=$form}

            <div class="well">

                <p>
                    Are you a user (mailbox owner) looking to change your <br />
                    password? If so, please click on this button:

                    <a style="float: right;" class="btn btn-primary" href="{genUrl controller="auth" action="change-password"}">Mailbox Password Change</a>
                </p>

            </div>


        </div>
    </div>

</div>
{tmplinclude file="footer.phtml"}
