{include file="header.phtml" }

<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn" id="modal-dialog-add_alias" href="{genUrl controller='alias' action='edit' mid=$mailboxModel.id modal=true}" title="Add Alias">
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	    <span class="btn-group" data-toggle="buttons-checkbox">
        	        <span class="btn {if $includeMailboxAliases}active{/if}" id="ima" title="Include mailbox aliases" >
            	        Include mailbox aliases
        	        </span>
            	</span>
        	</div>
    	</div>
        <h1>Aliases of {$mailboxModel.username}</h1>

    </div>
    {ViMbAdmin_Messages}


    <table id="mailbox_aliases_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Address</th>
                <th>Goto</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {foreach $aliases as $oneAlias}
            <tr id="alias_{$oneAlias.id}">
                <td>{$oneAlias.address}</td>
                <td id="alias-goto-{$oneAlias.id}">
                {$oneAlias.goto|shorten:50}
                {if strlen( $oneAlias.goto ) > 50 }
                    <script type="text/javascript">
                        $( document ).ready( function(){
                            $( "#alias-goto-{$oneAlias.id}" ).tooltip({ trigger: 'hover', delay: { show: 2000, hide: 100 }, title: '{$oneAlias.goto|regex_replace:"/[,]/":", "}' });
                        });
                    </script>
                {/if}
            </td>
                <td>
                    <span class="btn btn-mini" onclick="deleteAlias( {$oneAlias.id}, {$mailboxModel.id}, '{$oneAlias.address}' );" id="delete-alias-{$oneAlias.id}">Remove</span>
                </td>
            </tr>
        {/foreach}
        </tbody>
    </table>
    <br/>
    <br/>

    {include file='mailbox/js/aliases.js'}

    <div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to remove
        <em id="purge_alias_name"></em> from this entry?
    </div>
    <div id="pdfooter" class="modal-footer">
        <span class="btn btn-danger" id="purge_dialog_delete">Delete</span>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>


</div>
{include file="footer.phtml"}
