{include file="header.phtml" }

<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn" id="modal-dialog-add_alias" href="{genUrl controller='alias' action='edit' mid=$mailboxModel.id modal=true}" onmouseover="vm_tooltip( 'modal-dialog-add_alias', 'Add Alias' );">
            	        <i class="icon-plus"></i>
        	        </a>
        	        <span class="btn" id="ima" onmouseover="vm_tooltip( 'ima', '{if $includeMailboxAliases}Hide{else}Show{/if} Mailbox Aliases' );" >
            	        {if $includeMailboxAliases}
            	            <i class="icon-eye-close"></i>
            	        {else}
            	            <i class="icon-eye-open"></i>
            	        {/if}
        	        </span>
            	</span>
        	</div>
    	</div>
        <h1>Aliases of {$mailboxModel.username}</h1>

    </div>
    {ViMbAdmin_Messages}


    <table id="mailbox_aliases_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Address</th>
                <th>Goto</th>
                <th width="30"></th>
            </tr>
        </thead>
        <tbody>
        {foreach $aliases as $oneAlias}
            <tr id="alias_{$oneAlias.id}">
                <td>{$oneAlias.address}</td>
                <td id="alias-goto-{$oneAlias.id}" {if strlen( $oneAlias.goto ) > 50  } onmouseover="vm_tooltip( 'alias-goto-{$oneAlias.id}', '{$oneAlias.goto|regex_replace:"/[,]/":", "}' );" {/if}>
                {$oneAlias.goto|shorten:50}
            </td>
                <td>
                    <div class="btn-group">
                        <span class="btn btn-mini" onclick="deleteAlias( {$oneAlias.id}, {$mailboxModel.id}, '{$oneAlias.address}' );" id="delete-alias-{$oneAlias.id}" onmouseover="vm_tooltip( 'delete-alias-{$oneAlias.id}', 'Remove' );">
                            <i class="icon-trash"></i>
                        </span>
                    </div>
                </td>
            </tr>
        {/foreach}
        </tbody>
    </table>
    <br/>
    <br/>

    {include file='mailbox/js/aliases.js'}

    <div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to remove
        <em id="purge_alias_name"></em> from this entry?
    </div>
    <div id="pdfooter" class="modal-footer">
        <span class="btn btn-danger" id="purge_dialog_delete">Delete</span>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>


</div>
{include file="footer.phtml"}
