{include file="header.phtml" inColorBox=true}

<h1>Aliases of {$mailboxModel.username}</h1>

{ViMbAdmin_Messages}

<label><input type="checkbox" name="ima" id="ima" value="1" {if $includeMailboxAliases}checked="checked" {/if}/> Include mailbox aliases</label>

<br/>

<table id="mailbox_aliases_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Address</th>
            <th>Goto</th>
            <th>
                <a class="btn btn-mini" href="{genUrl controller='alias' action='edit' mid=$mailboxModel.id}">Add Alias</a>
            </th>
        </tr>
    </thead>
    <tbody>
    {foreach $aliases as $oneAlias}
        <tr id="alias_{$oneAlias.id}">
            <td>{$oneAlias.address}</td>
            <td>{$oneAlias.goto}</td>
            <td>
                <button class="btn btn-mini" onclick="deleteAlias({$oneAlias.id}, {$mailboxModel.id}, '{$mailboxModel.username}');">Remove</button>
            </td>
        </tr>
    {/foreach}
    </tbody>
</table>

{include file='mailbox/js/aliases.js'}

{include file="footer.phtml" inColorBox=true}
