{if !isset( $modal) || !$modal }
    {include file="header.phtml"}
    <div class="page-content" >
        <div class="page-header" >
            <h1>{if $mailboxModel.username}Edit mailbox {$mailboxModel.username}{else}New Mailbox{/if}</h1>
        </div>
        {ViMbAdmin_Messages}
{else}
<div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
            <h3>{if $mailboxModel.username}Edit mailbox {$mailboxModel.username}{else}New Mailbox{/if}</h3>
    </div>
    <div class="modal-body" style="min-height: 200px;">
{/if}

{$editForm}

{addJSValidator form=$editForm}

{if !isset( $modal) || !$modal }
    </div>
    {include file="footer.phtml"}
{else}
    </div>
    <div class="modal-footer" id="mtfooter">
        <button id="modal_dialog_save" class="btn btn-primary">{if $operation == 'Add'}Add{else}Save{/if}</button>
        <button id="modal_dialog_cancel" class="btn">Cancel</button>
        <script type="text/javascript">
    $(document).ready(function()
    {
        $('#modal_dialog_save').bind('click', function() {
            valid = true;
            var data = $('#modal_dialog').html();

            var Throb = tt_throbber( 32, 14, 1.8 ).appendTo( $( '#mtfooter' ).get(0) ).start();

            $('#modal_dialog_save').attr('disabled', 'disabled' ).addClass( 'disabled' );
            $('#modal_dialog_cancel').attr('disabled', 'disabled' ).addClass( 'disabled' );

            $.ajax({
                url: "{genUrl controller='mailbox' action='edit' mid=$mailboxModel.id}",
                data: $( '#mailbox_edit_form' ).serialize()+"&helper=0",
                async: true,
                cache: false,
                type: 'POST',
                timeout: 10000,
                success: function(data) {
                    if( data.trim() == "ok" ) {
                        dialog.modal('hide');
                        window.location.href = "{genUrl controller='mailbox' action='list'}/did/" + $( '#domain' ).val();
                    }
                    else if( data.substring(0, 26) == '<div class="modal-header">' ){
                        $('#modal_dialog').html( data );
                        $( '#modal_dialog_cancel' ).bind( 'click', function(){
                            dialog.modal('hide');
                        });

                        $( '#local_part' ).bind( 'change', function() { ossJscriptFieldValidator( 'local_part' ) } );
                        $( '#domain' ).bind( 'change', function() { ossJscriptFieldValidator( 'domain' ) } );
                        {if $operation == 'Add' }
                            $( '#password' ).bind( 'change', function() { ossJscriptFieldValidator( 'password' ) } );
                        {/if}
                    }
                    else {
                        dialog.modal('hide');
                        ossAddMessage( 'An unexpected error has occured.', 'error' );
                    }
                },
                error:   ossAjaxErrorHandler
            });
        });
    });
    </script>
    </div>

{/if}
