<div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
       <h3>Email Settings</h3>
</div>
<div class="modal-body" id="esbody">
    <p>Email settings for '<em>{$mailbox->getUsername()}</em>'.</p>
        {$form}
</div>

<div class="modal-footer" id="esfooter">
    <button id="modal_dialog_save" class="btn btn-primary">Send</button>
    <button id="modal_dialog_cancel" class="btn">Close</button>
</div>


<script type="text/javascript">
    $( 'document' ).ready( function() {

        $( '#modal_dialog_save' ).bind('click', function() {
            valid = true;
            var data = $('#modal_dialog').html();
            
            var Throb = tt_throbber( 32, 14, 1.8 ).appendTo( $( '#esfooter' ).get(0) ).start();

            $('#modal_dialog_save').attr('disabled', 'disabled' ).addClass( 'disabled' );
            $('#modal_dialog_cancel').attr('disabled', 'disabled' ).addClass( 'disabled' );

            $.ajax({
                url: "{genUrl controller='mailbox' action='email-settings' mid=$mailbox->getId()}/send/1",
                data: $( '#email_settings_form' ).serialize(),
                async: true,
                cache: false,
                type: 'POST',
                timeout: 10000,
                success: function(data) {
                    if( data == "ok" ) {
                        dialog.modal('hide');
                            location.reload();
                    }
                    else if( data == "error" ) {
                        dialog.modal('hide');
                            location.reload();
                    }
                    else if( data.substring(0, 26) == '<div class="modal-header">' ){
                        $('#modal_dialog').html( data );
                        $( '#modal_dialog_cancel' ).bind( 'click', function(){
                            dialog.modal('hide');
                        });
                    }
                    else {
                        dialog.modal('hide');
                        ossAddMessage( 'An unexpected error has occured.', 'error' );
                    }
                },
                error: ossAjaxErrorHandler
            });
        });
    });

</script>
