{include file="header.phtml"}

{assign var='purgeMailboxParams' value="open: true, iframe: true, transition: 'elastic', width: '580px', height: '600px'"}
{assign var='editMailboxParams' value="open: true, iframe: true, transition: 'elastic', width: '680px', height: '440px'"}
{assign var='aliasesParams' value="open: true, iframe: true, transition: 'elastic', width: '800px', height: '600px'"}
{assign var='mailboxPasswordParams' value="open: true, iframe: true, transition: 'elastic', width: '800px', height: '300px'"}


<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn" id="modal-dialog-add_mailbox" href="{genUrl controller='mailbox' action='edit' modal=true}{if $domain}/did/{$domain.id}{/if}" title="Add Mailbox">
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>
    	</div>

        <h1>Mailboxes {if $domain} for {$domain.domain} {if $domain.mailboxes neq 0}({$domain->countMailboxes()}/{$domain.mailboxes}){/if}{/if}</h1>
    </div>

{ViMbAdmin_Messages}

<table id="mailbox_list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Domain</th>
            <th>Active</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
{foreach $mailboxes as $oneMailbox}
        <tr>
            <td>{$oneMailbox.username}</td>
            <td>{$oneMailbox.name}</td>
            <td>{$oneMailbox.domain}</td>
            <td>
                <div id="throb-toggle-active-{$oneMailbox.id}" style="float: right;"></div>
                <span id="toggle-active-{$oneMailbox.id}" onclick="toggleActive( 'toggle-active-{$oneMailbox.id}', {$oneMailbox.id} );" class="btn btn-mini {if $oneMailbox.active}btn-success{else}btn-danger{/if}">{$oneMailbox.active|yesno}</span>
            </td>
            <td>
                <a class="btn btn-mini" href="{genUrl controller='mailbox' action='aliases' mid=$oneMailbox.id}">Aliases</a>
                <a class="btn btn-mini" id="modal-dialog-wide-purge_{$oneMailbox.id}" href="{genUrl controller='mailbox' action='purge' mid=$oneMailbox.id modal=true}">Purge</a>
                <a class="btn btn-mini" id="modal-dialog-wide-password_{$oneMailbox.id}" href="{genUrl controller='mailbox' action='password' mid=$oneMailbox.id modal=true}">Password</a>
                <a class="btn btn-mini" id="modal-dialog-wide-edit_mailbox_{$oneMailbox.id}" href="{genUrl controller='mailbox' action='edit' mid=$oneMailbox.id modal=true}">Edit</a>
                <span class="btn btn-mini" onclick="sendEmail( {$oneMailbox.id}, '{$oneMailbox.username}' );" id="send-email-{$oneMailbox.id}">Email Settings</span>
            </td>
        </tr>
{/foreach}
    </tbody>
</table>

<br />
<br />

{include file='mailbox/js/list.js'}


<div id="email_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to send email settings for <em id="email_name"> </em>?
    </div>
    <div id="efooter" class="modal-footer">
        <span class="btn btn-primary" id="email_dialog_send">Send</span>
        <button id="email_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

</div>

{include file="footer.phtml"}
