{include file="header.phtml"}

{assign var='purgeMailboxParams' value="open: true, iframe: true, transition: 'elastic', width: '580px', height: '600px'"}
{assign var='editMailboxParams' value="open: true, iframe: true, transition: 'elastic', width: '680px', height: '440px'"}
{assign var='aliasesParams' value="open: true, iframe: true, transition: 'elastic', width: '800px', height: '600px'"}
{assign var='mailboxPasswordParams' value="open: true, iframe: true, transition: 'elastic', width: '800px', height: '300px'"}


<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
            	<span class="btn-group">
        	        <a class="btn" id="modal-dialog-email_add_mailbox" title="Add Mailbox" href="{genUrl controller='mailbox' action='edit' modal=true}{if $domain}/did/{$domain.id}{/if}" title="Add Mailbox">
            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
            	<script>
                    $( document ).ready( function(){
                        $( '#modal-dialog-add_mailbox' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover', placement: 'bottom' } );
                    });
                </script>
        	</div>
    	</div>

        <h1>
            Mailboxes {if $domain}<small> for {$domain.domain} {if $domain.mailboxes neq 0}({$domain->countMailboxes()}/{$domain.mailboxes}){/if}</small>{/if}
            {if isset( $session->domain ) && $session->domain}
                <a class="btn" id="show_all_mailbox" title="Show All" href="{genUrl controller='mailbox' action='list' unset=1}">
                    <i class="icon-remove-circle"></i>
                </a>
                <script>
                    $( document ).ready( function(){
                        $( '#show_all_mailbox' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover', placement: 'bottom' } );
                    });
                </script>
            {/if}
        </h1>
    </div>

{ViMbAdmin_Messages}

<table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Domain</th>
            <th width="55">Active</th>
            <th width="140"></th>
        </tr>
    </thead>
    <tbody>
{foreach $mailboxes as $oneMailbox}
        <tr>
            <td>{$oneMailbox.username}</td>
            <td>{$oneMailbox.name}</td>
            <td>{$oneMailbox.domain}</td>
            <td>
                <div id="throb-toggle-active-{$oneMailbox.id}" style="float: right;"></div>
                <span id="toggle-active-{$oneMailbox.id}" onclick="toggleActive( 'toggle-active-{$oneMailbox.id}', {$oneMailbox.id} );" class="btn btn-mini {if $oneMailbox.active}btn-success{else}btn-danger{/if}">{$oneMailbox.active|yesno}</span>
            </td>
            <td>
                <div class="btn-group">
                    <a class="btn btn-mini" id="modal-dialog-email_edit_mailbox_{$oneMailbox.id}" title="Edit" href="{genUrl controller='mailbox' action='edit' mid=$oneMailbox.id modal=true}">
                        <i class="icon-pencil"></i>
                    </a>
                    <a class="btn btn-mini" id="modal-dialog-password_{$oneMailbox.id}" title="Password" href="{genUrl controller='mailbox' action='password' mid=$oneMailbox.id modal=true}">
                        <i class="icon-lock"></i>
                    </a>
                    <a class="btn btn-mini" id="mailbox_aliases_{$oneMailbox.id}" title="List Aliases" href="{genUrl controller='mailbox' action='aliases' mid=$oneMailbox.id}">
                        <i class="icon-random"></i>
                    </a>
                    <span class="btn btn-mini" id="mailbox_settings_{$oneMailbox.id}" title="Send Settings" onclick="sendEmail( {$oneMailbox.id}, '{$oneMailbox.username}' );" id="send-email-{$oneMailbox.id}">
                        <i class="icon-envelope"></i>
                    </span>
                    <a class="btn btn-mini" id="modal-dialog-purge_{$oneMailbox.id}" title="Purge" href="{genUrl controller='mailbox' action='purge' mid=$oneMailbox.id modal=true}">
                        <i class="icon-trash"></i>
                    </a>
                </div>
                <script>
                    $( document ).ready( function(){
                        $( '#modal-dialog-edit_mailbox_{$oneMailbox.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                        $( '#modal-dialog-password_{$oneMailbox.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                        $( '#mailbox_aliases_{$oneMailbox.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                        $( '#mailbox_settings_{$oneMailbox.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                        $( '#modal-dialog-purge_{$oneMailbox.id}' ).tooltip( { delay: { show: 500, hide: 2 }, trigger: 'hover' } );
                    });
                </script>
            </td>
        </tr>
{/foreach}
    </tbody>
</table>

<br />
<br />

{include file='mailbox/js/list.js'}


<div id="email_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to send email settings for <em id="email_name"> </em>?
    </div>
    <div id="efooter" class="modal-footer">
        <span class="btn btn-primary" id="email_dialog_send">Send</span>
        <button id="email_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

</div>

{include file="footer.phtml"}
