{tmplinclude file="header.phtml"}
<div class="page-content" >
    <div class="page-header" >
        <h1>Purge Mailbox <small>{$mailbox->getUsername()}</small></h1>
    </div>
    {OSS_Message}


    You are about to delete the mailbox <b>{$mailbox->getUsername()}</b>

    <br />
    <br />


    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
        <thead>
            <tr class="dark_row">
                <th colspan="2" class="center">Aliases</th>
            </tr>
        </thead>
    {if count( $aliases ) > 0 }
            <tr>
                <td class="bold">Address</td>
                <td class="bold">Goto</td>
            </tr>
        {foreach $aliases as $alias}
            <tr>
                <td>{$alias->getAddress()}</td>
                <td>{$alias->getGoto()}</td>
            </tr>
        {/foreach}
    {else}
        <tr>
            <td class="bold" colspan="2">There are no aliases.</td>
        </tr>
    {/if}
    </table>

    <br />

    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
        <thead>
            <tr class="dark_row">
                <th colspan="2" class="center">In aliases</th>
            </tr>
        </thead>
    {if count( $inAliases ) > 0 }
            <tr>
                <td class="bold">Address</td>
                <td class="bold">Goto</td>
            </tr>
        {foreach $inAliases as $alias}
            <tr>
                <td>{$alias->getAddress()}</td>
                <td>
                    <div id="alias-goto-{$alias->getId()}" {if strlen( $alias->getGoto() ) > 50 } class="have-tooltip-long" title="{$alias->getGoto()|regex_replace:"/[,]/":", "}"{/if}>
                        {$alias->getGoto()|shorten:50}
                    </div>
                </td>
            </tr>
        {/foreach}
    {else}
        <tr>
            <td class="bold" colspan="2">This mailbox is not used in any alias.</td>
        </tr>
    {/if}
    </table>

    <br />

    <strong>The mailbox and all aliases where this mailbox is the sole recipient will be deleted. This mailbox 
       will be removed from any alias where it is one of two or more destinations.</strong>

    <br />
    <br />

    <form name="purge_mailbox_form" id="purge_mailbox_form" method="post" action="">
        <fieldset class="form-actions">
            <label class="checkbox">
                <input type="checkbox" value="1" checked="checked" id="cb_delete_files" name="delete_files" />
                Delete the home directory and mailbox files also
            </label>
            <br />
            <a class="btn" href="{genUrl controller='mailbox' action='list'}">Cancel</a>
            <button class="btn btn-danger" type="submit" value="purge" name="purge">Purge</button>
        </fieldset>
    </form>


</div>
{tmplinclude file="footer.phtml"}
