<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mailbox extends \Entities\Mailbox implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'username', 'password', 'name', 'alt_email', 'quota', 'local_part', 'active', 'access_restriction', 'homedir', 'maildir', 'uid', 'gid', 'created', 'modified', 'id', 'Preferences', 'homedir_size', 'maildir_size', 'size_at', 'Domain', 'DirectoryEntry', 'delete_pending', '_className', '_preferenceClassName', '_cache', '_namespace');
        }

        return array('__isInitialized__', 'username', 'password', 'name', 'alt_email', 'quota', 'local_part', 'active', 'access_restriction', 'homedir', 'maildir', 'uid', 'gid', 'created', 'modified', 'id', 'Preferences', 'homedir_size', 'maildir_size', 'size_at', 'Domain', 'DirectoryEntry', 'delete_pending', '_className', '_preferenceClassName', '_cache', '_namespace');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mailbox $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAltEmail($altEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltEmail', array($altEmail));

        return parent::setAltEmail($altEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAltEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltEmail', array());

        return parent::getAltEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuota($quota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuota', array($quota));

        return parent::setQuota($quota);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuota', array());

        return parent::getQuota();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalPart($localPart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalPart', array($localPart));

        return parent::setLocalPart($localPart);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalPart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalPart', array());

        return parent::getLocalPart();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessRestriction($accessRestriction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessRestriction', array($accessRestriction));

        return parent::setAccessRestriction($accessRestriction);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessRestriction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessRestriction', array());

        return parent::getAccessRestriction();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomedir($homedir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomedir', array($homedir));

        return parent::setHomedir($homedir);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomedir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomedir', array());

        return parent::getHomedir();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaildir($maildir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaildir', array($maildir));

        return parent::setMaildir($maildir);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaildir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaildir', array());

        return parent::getMaildir();
    }

    /**
     * {@inheritDoc}
     */
    public function getCleanedMaildir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCleanedMaildir', array());

        return parent::getCleanedMaildir();
    }

    /**
     * {@inheritDoc}
     */
    public function setUid($uid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUid', array($uid));

        return parent::setUid($uid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', array());

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGid($gid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGid', array($gid));

        return parent::setGid($gid);
    }

    /**
     * {@inheritDoc}
     */
    public function getGid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGid', array());

        return parent::getGid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setModified($modified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModified', array($modified));

        return parent::setModified($modified);
    }

    /**
     * {@inheritDoc}
     */
    public function getModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModified', array());

        return parent::getModified();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addPreference(\Entities\MailboxPreference $preferences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreference', array($preferences));

        return parent::addPreference($preferences);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreference(\Entities\MailboxPreference $preferences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreference', array($preferences));

        return parent::removePreference($preferences);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferences', array());

        return parent::getPreferences();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain(\Entities\Domain $domain = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', array($domain));

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', array());

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function addMailboxPreference(\Entities\MailboxPreference $preferences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMailboxPreference', array($preferences));

        return parent::addMailboxPreference($preferences);
    }

    /**
     * {@inheritDoc}
     */
    public function formatMaildir($maildir = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'formatMaildir', array($maildir));

        return parent::formatMaildir($maildir);
    }

    /**
     * {@inheritDoc}
     */
    public function formatHomedir($homedir = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'formatHomedir', array($homedir));

        return parent::formatHomedir($homedir);
    }

    /**
     * {@inheritDoc}
     */
    public function setHomedirSize($homedirSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomedirSize', array($homedirSize));

        return parent::setHomedirSize($homedirSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomedirSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomedirSize', array());

        return parent::getHomedirSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaildirSize($maildirSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaildirSize', array($maildirSize));

        return parent::setMaildirSize($maildirSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaildirSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaildirSize', array());

        return parent::getMaildirSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSizeAt($sizeAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSizeAt', array($sizeAt));

        return parent::setSizeAt($sizeAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSizeAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSizeAt', array());

        return parent::getSizeAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirectoryEntry(\Entities\DirectoryEntry $directoryEntry = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirectoryEntry', array($directoryEntry));

        return parent::setDirectoryEntry($directoryEntry);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirectoryEntry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirectoryEntry', array());

        return parent::getDirectoryEntry();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletePending($deletePending)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletePending', array($deletePending));

        return parent::setDeletePending($deletePending);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletePending()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletePending', array());

        return parent::getDeletePending();
    }

    /**
     * {@inheritDoc}
     */
    public function loadPreference($attribute, $index = 0, $includeExpired = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadPreference', array($attribute, $index, $includeExpired));

        return parent::loadPreference($attribute, $index, $includeExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function hasPreference($attribute, $index = 0, $includeExpired = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPreference', array($attribute, $index, $includeExpired));

        return parent::hasPreference($attribute, $index, $includeExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreference($attribute, $index = 0, $includeExpired = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreference', array($attribute, $index, $includeExpired));

        return parent::getPreference($attribute, $index, $includeExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function setPreference($attribute, $value, $operator = '=', $expires = 0, $index = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreference', array($attribute, $value, $operator, $expires, $index));

        return parent::setPreference($attribute, $value, $operator, $expires, $index);
    }

    /**
     * {@inheritDoc}
     */
    public function addIndexedPreference($attribute, $value, $operator = '=', $expires = 0, $max = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIndexedPreference', array($attribute, $value, $operator, $expires, $max));

        return parent::addIndexedPreference($attribute, $value, $operator, $expires, $max);
    }

    /**
     * {@inheritDoc}
     */
    public function cleanExpiredPreferences($asOf = NULL, $attribute = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cleanExpiredPreferences', array($asOf, $attribute));

        return parent::cleanExpiredPreferences($asOf, $attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function deletePreference($attribute, $index = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deletePreference', array($attribute, $index));

        return parent::deletePreference($attribute, $index);
    }

    /**
     * {@inheritDoc}
     */
    public function expungePreferences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'expungePreferences', array());

        return parent::expungePreferences();
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexedPreference($attribute, $withIndex = false, $ignoreExpired = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexedPreference', array($attribute, $withIndex, $ignoreExpired));

        return parent::getIndexedPreference($attribute, $withIndex, $ignoreExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssocPreference($attribute, $index = NULL, $ignoreExpired = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssocPreference', array($attribute, $index, $ignoreExpired));

        return parent::getAssocPreference($attribute, $index, $ignoreExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function deleteAssocPreference($attribute, $index = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteAssocPreference', array($attribute, $index));

        return parent::deleteAssocPreference($attribute, $index);
    }

    /**
     * {@inheritDoc}
     */
    public function _getPreferences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_getPreferences', array());

        return parent::_getPreferences();
    }

}
