<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DirectoryEntry extends \Entities\DirectoryEntry implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'businessCategory', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'carLicense', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'departmentNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'displayName', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'employeeNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'employeeType', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'homePhone', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'homePostalAddress', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'initials', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'jpegPhoto', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'labeledURI', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'mail', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'manager', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'mobile', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'o', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'pager', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'preferredLanguage', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'roomNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'secretary', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'personalTitle', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'sn', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'ou', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'title', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'facsimileTelephoneNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'givenName', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'telephoneNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'vimb_created', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'vimb_update', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'id', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'Mailbox'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'businessCategory', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'carLicense', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'departmentNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'displayName', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'employeeNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'employeeType', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'homePhone', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'homePostalAddress', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'initials', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'jpegPhoto', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'labeledURI', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'mail', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'manager', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'mobile', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'o', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'pager', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'preferredLanguage', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'roomNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'secretary', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'personalTitle', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'sn', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'ou', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'title', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'facsimileTelephoneNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'givenName', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'telephoneNumber', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'vimb_created', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'vimb_update', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'id', '' . "\0" . 'Entities\\DirectoryEntry' . "\0" . 'Mailbox'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DirectoryEntry $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setBusinessCategory($businessCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessCategory', [$businessCategory]);

        return parent::setBusinessCategory($businessCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessCategory', []);

        return parent::getBusinessCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarLicense($carLicense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarLicense', [$carLicense]);

        return parent::setCarLicense($carLicense);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarLicense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarLicense', []);

        return parent::getCarLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartmentNumber($departmentNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartmentNumber', [$departmentNumber]);

        return parent::setDepartmentNumber($departmentNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartmentNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartmentNumber', []);

        return parent::getDepartmentNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', [$displayName]);

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', []);

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeNumber($employeeNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeNumber', [$employeeNumber]);

        return parent::setEmployeeNumber($employeeNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeNumber', []);

        return parent::getEmployeeNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeType($employeeType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeType', [$employeeType]);

        return parent::setEmployeeType($employeeType);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeType', []);

        return parent::getEmployeeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomePhone($homePhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomePhone', [$homePhone]);

        return parent::setHomePhone($homePhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomePhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomePhone', []);

        return parent::getHomePhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomePostalAddress($homePostalAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomePostalAddress', [$homePostalAddress]);

        return parent::setHomePostalAddress($homePostalAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomePostalAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomePostalAddress', []);

        return parent::getHomePostalAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitials($initials)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitials', [$initials]);

        return parent::setInitials($initials);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitials', []);

        return parent::getInitials();
    }

    /**
     * {@inheritDoc}
     */
    public function setJpegPhoto($jpegPhoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJpegPhoto', [$jpegPhoto]);

        return parent::setJpegPhoto($jpegPhoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getJpegPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJpegPhoto', []);

        return parent::getJpegPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabeledURI($labeledURI)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabeledURI', [$labeledURI]);

        return parent::setLabeledURI($labeledURI);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabeledURI()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabeledURI', []);

        return parent::getLabeledURI();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setManager($manager)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManager', [$manager]);

        return parent::setManager($manager);
    }

    /**
     * {@inheritDoc}
     */
    public function getManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManager', []);

        return parent::getManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', [$mobile]);

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', []);

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setO($o)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setO', [$o]);

        return parent::setO($o);
    }

    /**
     * {@inheritDoc}
     */
    public function getO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getO', []);

        return parent::getO();
    }

    /**
     * {@inheritDoc}
     */
    public function setPager($pager)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPager', [$pager]);

        return parent::setPager($pager);
    }

    /**
     * {@inheritDoc}
     */
    public function getPager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPager', []);

        return parent::getPager();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferredLanguage($preferredLanguage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferredLanguage', [$preferredLanguage]);

        return parent::setPreferredLanguage($preferredLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferredLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferredLanguage', []);

        return parent::getPreferredLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomNumber($roomNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomNumber', [$roomNumber]);

        return parent::setRoomNumber($roomNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomNumber', []);

        return parent::getRoomNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecretary($secretary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecretary', [$secretary]);

        return parent::setSecretary($secretary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecretary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecretary', []);

        return parent::getSecretary();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonalTitle($personalTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonalTitle', [$personalTitle]);

        return parent::setPersonalTitle($personalTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonalTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonalTitle', []);

        return parent::getPersonalTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSn($sn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSn', [$sn]);

        return parent::setSn($sn);
    }

    /**
     * {@inheritDoc}
     */
    public function getSn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSn', []);

        return parent::getSn();
    }

    /**
     * {@inheritDoc}
     */
    public function setOu($ou)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOu', [$ou]);

        return parent::setOu($ou);
    }

    /**
     * {@inheritDoc}
     */
    public function getOu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOu', []);

        return parent::getOu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacsimileTelephoneNumber($facsimileTelephoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacsimileTelephoneNumber', [$facsimileTelephoneNumber]);

        return parent::setFacsimileTelephoneNumber($facsimileTelephoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacsimileTelephoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacsimileTelephoneNumber', []);

        return parent::getFacsimileTelephoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setGivenName($givenName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGivenName', [$givenName]);

        return parent::setGivenName($givenName);
    }

    /**
     * {@inheritDoc}
     */
    public function getGivenName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGivenName', []);

        return parent::getGivenName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneNumber($telephoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneNumber', [$telephoneNumber]);

        return parent::setTelephoneNumber($telephoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneNumber', []);

        return parent::getTelephoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setVimbCreated($vimbCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVimbCreated', [$vimbCreated]);

        return parent::setVimbCreated($vimbCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getVimbCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVimbCreated', []);

        return parent::getVimbCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setVimbUpdate($vimbUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVimbUpdate', [$vimbUpdate]);

        return parent::setVimbUpdate($vimbUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getVimbUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVimbUpdate', []);

        return parent::getVimbUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailbox(\Entities\Mailbox $mailbox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailbox', [$mailbox]);

        return parent::setMailbox($mailbox);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailbox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailbox', []);

        return parent::getMailbox();
    }

}
