<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DirectoryEntry extends \Entities\DirectoryEntry implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'businessCategory', 'carLicense', 'departmentNumber', 'displayName', 'employeeNumber', 'employeeType', 'homePhone', 'homePostalAddress', 'initials', 'jpegPhoto', 'labeledURI', 'mail', 'manager', 'mobile', 'o', 'pager', 'preferredLanguage', 'roomNumber', 'secretary', 'personalTitle', 'sn', 'ou', 'title', 'facsimileTelephoneNumber', 'givenName', 'telephoneNumber', 'vimb_created', 'vimb_update', 'id', 'Mailbox');
        }

        return array('__isInitialized__', 'businessCategory', 'carLicense', 'departmentNumber', 'displayName', 'employeeNumber', 'employeeType', 'homePhone', 'homePostalAddress', 'initials', 'jpegPhoto', 'labeledURI', 'mail', 'manager', 'mobile', 'o', 'pager', 'preferredLanguage', 'roomNumber', 'secretary', 'personalTitle', 'sn', 'ou', 'title', 'facsimileTelephoneNumber', 'givenName', 'telephoneNumber', 'vimb_created', 'vimb_update', 'id', 'Mailbox');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DirectoryEntry $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setBusinessCategory($businessCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessCategory', array($businessCategory));

        return parent::setBusinessCategory($businessCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessCategory', array());

        return parent::getBusinessCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarLicense($carLicense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarLicense', array($carLicense));

        return parent::setCarLicense($carLicense);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarLicense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarLicense', array());

        return parent::getCarLicense();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartmentNumber($departmentNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartmentNumber', array($departmentNumber));

        return parent::setDepartmentNumber($departmentNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartmentNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartmentNumber', array());

        return parent::getDepartmentNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName($displayName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', array($displayName));

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', array());

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeNumber($employeeNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeNumber', array($employeeNumber));

        return parent::setEmployeeNumber($employeeNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeNumber', array());

        return parent::getEmployeeNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmployeeType($employeeType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmployeeType', array($employeeType));

        return parent::setEmployeeType($employeeType);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmployeeType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmployeeType', array());

        return parent::getEmployeeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomePhone($homePhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomePhone', array($homePhone));

        return parent::setHomePhone($homePhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomePhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomePhone', array());

        return parent::getHomePhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomePostalAddress($homePostalAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomePostalAddress', array($homePostalAddress));

        return parent::setHomePostalAddress($homePostalAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomePostalAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomePostalAddress', array());

        return parent::getHomePostalAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitials($initials)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitials', array($initials));

        return parent::setInitials($initials);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitials', array());

        return parent::getInitials();
    }

    /**
     * {@inheritDoc}
     */
    public function setJpegPhoto($jpegPhoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJpegPhoto', array($jpegPhoto));

        return parent::setJpegPhoto($jpegPhoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getJpegPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJpegPhoto', array());

        return parent::getJpegPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabeledURI($labeledURI)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabeledURI', array($labeledURI));

        return parent::setLabeledURI($labeledURI);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabeledURI()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabeledURI', array());

        return parent::getLabeledURI();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', array($mail));

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array());

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setManager($manager)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManager', array($manager));

        return parent::setManager($manager);
    }

    /**
     * {@inheritDoc}
     */
    public function getManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManager', array());

        return parent::getManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setO($o)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setO', array($o));

        return parent::setO($o);
    }

    /**
     * {@inheritDoc}
     */
    public function getO()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getO', array());

        return parent::getO();
    }

    /**
     * {@inheritDoc}
     */
    public function setPager($pager)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPager', array($pager));

        return parent::setPager($pager);
    }

    /**
     * {@inheritDoc}
     */
    public function getPager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPager', array());

        return parent::getPager();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferredLanguage($preferredLanguage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferredLanguage', array($preferredLanguage));

        return parent::setPreferredLanguage($preferredLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferredLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferredLanguage', array());

        return parent::getPreferredLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomNumber($roomNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomNumber', array($roomNumber));

        return parent::setRoomNumber($roomNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomNumber', array());

        return parent::getRoomNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecretary($secretary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecretary', array($secretary));

        return parent::setSecretary($secretary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecretary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecretary', array());

        return parent::getSecretary();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonalTitle($personalTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonalTitle', array($personalTitle));

        return parent::setPersonalTitle($personalTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonalTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonalTitle', array());

        return parent::getPersonalTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSn($sn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSn', array($sn));

        return parent::setSn($sn);
    }

    /**
     * {@inheritDoc}
     */
    public function getSn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSn', array());

        return parent::getSn();
    }

    /**
     * {@inheritDoc}
     */
    public function setOu($ou)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOu', array($ou));

        return parent::setOu($ou);
    }

    /**
     * {@inheritDoc}
     */
    public function getOu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOu', array());

        return parent::getOu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacsimileTelephoneNumber($facsimileTelephoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacsimileTelephoneNumber', array($facsimileTelephoneNumber));

        return parent::setFacsimileTelephoneNumber($facsimileTelephoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacsimileTelephoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacsimileTelephoneNumber', array());

        return parent::getFacsimileTelephoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setGivenName($givenName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGivenName', array($givenName));

        return parent::setGivenName($givenName);
    }

    /**
     * {@inheritDoc}
     */
    public function getGivenName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGivenName', array());

        return parent::getGivenName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneNumber($telephoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneNumber', array($telephoneNumber));

        return parent::setTelephoneNumber($telephoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneNumber', array());

        return parent::getTelephoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setVimbCreated($vimbCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVimbCreated', array($vimbCreated));

        return parent::setVimbCreated($vimbCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getVimbCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVimbCreated', array());

        return parent::getVimbCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setVimbUpdate($vimbUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVimbUpdate', array($vimbUpdate));

        return parent::setVimbUpdate($vimbUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getVimbUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVimbUpdate', array());

        return parent::getVimbUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailbox(\Entities\Mailbox $mailbox)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailbox', array($mailbox));

        return parent::setMailbox($mailbox);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailbox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailbox', array());

        return parent::getMailbox();
    }

}
