<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Domain extends \Entities\Domain implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'domain', 'description', 'quota', 'transport', 'backupmx', 'active', 'homedir', 'maildir', 'uid', 'gid', 'created', 'modified', 'id', 'max_quota', 'max_aliases', 'max_mailboxes', 'alias_count', 'mailbox_count', 'Mailboxes', 'Aliases', 'Logs', 'Admins', 'Preferences', 'Archives', '_className', '_preferenceClassName', '_cache', '_namespace');
        }

        return array('__isInitialized__', 'domain', 'description', 'quota', 'transport', 'backupmx', 'active', 'homedir', 'maildir', 'uid', 'gid', 'created', 'modified', 'id', 'max_quota', 'max_aliases', 'max_mailboxes', 'alias_count', 'mailbox_count', 'Mailboxes', 'Aliases', 'Logs', 'Admins', 'Preferences', 'Archives', '_className', '_preferenceClassName', '_cache', '_namespace');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Domain $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDomain($domain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', array($domain));

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', array());

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getAliases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAliases', array());

        return parent::getAliases();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailboxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailboxes', array());

        return parent::getMailboxes();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuota($quota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuota', array($quota));

        return parent::setQuota($quota);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuota', array());

        return parent::getQuota();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransport($transport)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransport', array($transport));

        return parent::setTransport($transport);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransport', array());

        return parent::getTransport();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackupmx($backupmx)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackupmx', array($backupmx));

        return parent::setBackupmx($backupmx);
    }

    /**
     * {@inheritDoc}
     */
    public function getBackupmx()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBackupmx', array());

        return parent::getBackupmx();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomedir($homedir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomedir', array($homedir));

        return parent::setHomedir($homedir);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomedir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomedir', array());

        return parent::getHomedir();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaildir($maildir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaildir', array($maildir));

        return parent::setMaildir($maildir);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaildir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaildir', array());

        return parent::getMaildir();
    }

    /**
     * {@inheritDoc}
     */
    public function setUid($uid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUid', array($uid));

        return parent::setUid($uid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', array());

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGid($gid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGid', array($gid));

        return parent::setGid($gid);
    }

    /**
     * {@inheritDoc}
     */
    public function getGid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGid', array());

        return parent::getGid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setModified($modified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModified', array($modified));

        return parent::setModified($modified);
    }

    /**
     * {@inheritDoc}
     */
    public function getModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModified', array());

        return parent::getModified();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addMailbox(\Entities\Mailbox $mailboxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMailbox', array($mailboxes));

        return parent::addMailbox($mailboxes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMailbox(\Entities\Mailbox $mailboxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMailbox', array($mailboxes));

        return parent::removeMailbox($mailboxes);
    }

    /**
     * {@inheritDoc}
     */
    public function addAlias(\Entities\Alias $aliases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlias', array($aliases));

        return parent::addAlias($aliases);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAlias(\Entities\Alias $aliases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAlias', array($aliases));

        return parent::removeAlias($aliases);
    }

    /**
     * {@inheritDoc}
     */
    public function addLog(\Entities\Log $logs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLog', array($logs));

        return parent::addLog($logs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLog(\Entities\Log $logs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLog', array($logs));

        return parent::removeLog($logs);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogs', array());

        return parent::getLogs();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdmin(\Entities\Admin $admins)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdmin', array($admins));

        return parent::addAdmin($admins);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdmin(\Entities\Admin $admins)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdmin', array($admins));

        return parent::removeAdmin($admins);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmins()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmins', array());

        return parent::getAdmins();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxAliases($maxAliases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxAliases', array($maxAliases));

        return parent::setMaxAliases($maxAliases);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxAliases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxAliases', array());

        return parent::getMaxAliases();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxMailboxes($maxMailboxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxMailboxes', array($maxMailboxes));

        return parent::setMaxMailboxes($maxMailboxes);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxMailboxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxMailboxes', array());

        return parent::getMaxMailboxes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxQuota($maxQuota)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxQuota', array($maxQuota));

        return parent::setMaxQuota($maxQuota);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxQuota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxQuota', array());

        return parent::getMaxQuota();
    }

    /**
     * {@inheritDoc}
     */
    public function setAliasCount($aliasCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAliasCount', array($aliasCount));

        return parent::setAliasCount($aliasCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAliasCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAliasCount', array());

        return parent::getAliasCount();
    }

    /**
     * {@inheritDoc}
     */
    public function increaseAliasCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'increaseAliasCount', array());

        return parent::increaseAliasCount();
    }

    /**
     * {@inheritDoc}
     */
    public function decreaseAliasCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decreaseAliasCount', array());

        return parent::decreaseAliasCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailboxCount($mailboxCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailboxCount', array($mailboxCount));

        return parent::setMailboxCount($mailboxCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailboxCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailboxCount', array());

        return parent::getMailboxCount();
    }

    /**
     * {@inheritDoc}
     */
    public function increaseMailboxCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'increaseMailboxCount', array());

        return parent::increaseMailboxCount();
    }

    /**
     * {@inheritDoc}
     */
    public function decreaseMailboxCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decreaseMailboxCount', array());

        return parent::decreaseMailboxCount();
    }

    /**
     * {@inheritDoc}
     */
    public function addMailboxe(\Entities\Mailbox $mailboxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMailboxe', array($mailboxes));

        return parent::addMailboxe($mailboxes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMailboxe(\Entities\Mailbox $mailboxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMailboxe', array($mailboxes));

        return parent::removeMailboxe($mailboxes);
    }

    /**
     * {@inheritDoc}
     */
    public function addAliase(\Entities\Alias $aliases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAliase', array($aliases));

        return parent::addAliase($aliases);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAliase(\Entities\Alias $aliases)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAliase', array($aliases));

        return parent::removeAliase($aliases);
    }

    /**
     * {@inheritDoc}
     */
    public function addPreference(\Entities\DomainPreference $preferences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPreference', array($preferences));

        return parent::addPreference($preferences);
    }

    /**
     * {@inheritDoc}
     */
    public function removePreference(\Entities\DomainPreference $preferences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePreference', array($preferences));

        return parent::removePreference($preferences);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferences', array());

        return parent::getPreferences();
    }

    /**
     * {@inheritDoc}
     */
    public function addArchive(\Entities\Archive $archives)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArchive', array($archives));

        return parent::addArchive($archives);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArchive(\Entities\Archive $archives)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArchive', array($archives));

        return parent::removeArchive($archives);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchives()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchives', array());

        return parent::getArchives();
    }

    /**
     * {@inheritDoc}
     */
    public function loadPreference($attribute, $index = 0, $includeExpired = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadPreference', array($attribute, $index, $includeExpired));

        return parent::loadPreference($attribute, $index, $includeExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function hasPreference($attribute, $index = 0, $includeExpired = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPreference', array($attribute, $index, $includeExpired));

        return parent::hasPreference($attribute, $index, $includeExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreference($attribute, $index = 0, $includeExpired = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreference', array($attribute, $index, $includeExpired));

        return parent::getPreference($attribute, $index, $includeExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function setPreference($attribute, $value, $operator = '=', $expires = 0, $index = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreference', array($attribute, $value, $operator, $expires, $index));

        return parent::setPreference($attribute, $value, $operator, $expires, $index);
    }

    /**
     * {@inheritDoc}
     */
    public function addIndexedPreference($attribute, $value, $operator = '=', $expires = 0, $max = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIndexedPreference', array($attribute, $value, $operator, $expires, $max));

        return parent::addIndexedPreference($attribute, $value, $operator, $expires, $max);
    }

    /**
     * {@inheritDoc}
     */
    public function cleanExpiredPreferences($asOf = NULL, $attribute = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cleanExpiredPreferences', array($asOf, $attribute));

        return parent::cleanExpiredPreferences($asOf, $attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function deletePreference($attribute, $index = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deletePreference', array($attribute, $index));

        return parent::deletePreference($attribute, $index);
    }

    /**
     * {@inheritDoc}
     */
    public function expungePreferences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'expungePreferences', array());

        return parent::expungePreferences();
    }

    /**
     * {@inheritDoc}
     */
    public function getIndexedPreference($attribute, $withIndex = false, $ignoreExpired = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndexedPreference', array($attribute, $withIndex, $ignoreExpired));

        return parent::getIndexedPreference($attribute, $withIndex, $ignoreExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssocPreference($attribute, $index = NULL, $ignoreExpired = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssocPreference', array($attribute, $index, $ignoreExpired));

        return parent::getAssocPreference($attribute, $index, $ignoreExpired);
    }

    /**
     * {@inheritDoc}
     */
    public function deleteAssocPreference($attribute, $index = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteAssocPreference', array($attribute, $index));

        return parent::deleteAssocPreference($attribute, $index);
    }

    /**
     * {@inheritDoc}
     */
    public function _getPreferences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_getPreferences', array());

        return parent::_getPreferences();
    }

}
