<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Archive extends \Entities\Archive implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Archive' . "\0" . 'username', '' . "\0" . 'Entities\\Archive' . "\0" . 'status', '' . "\0" . 'Entities\\Archive' . "\0" . 'archived_at', '' . "\0" . 'Entities\\Archive' . "\0" . 'status_changed_at', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_server', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_file', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_orig_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_server', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_file', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_orig_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'data', '' . "\0" . 'Entities\\Archive' . "\0" . 'id', '' . "\0" . 'Entities\\Archive' . "\0" . 'Domain', '' . "\0" . 'Entities\\Archive' . "\0" . 'ArchivedBy'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Archive' . "\0" . 'username', '' . "\0" . 'Entities\\Archive' . "\0" . 'status', '' . "\0" . 'Entities\\Archive' . "\0" . 'archived_at', '' . "\0" . 'Entities\\Archive' . "\0" . 'status_changed_at', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_server', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_file', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_orig_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'homedir_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_server', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_file', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_orig_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'maildir_size', '' . "\0" . 'Entities\\Archive' . "\0" . 'data', '' . "\0" . 'Entities\\Archive' . "\0" . 'id', '' . "\0" . 'Entities\\Archive' . "\0" . 'Domain', '' . "\0" . 'Entities\\Archive' . "\0" . 'ArchivedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Archive $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchivedAt($archivedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchivedAt', [$archivedAt]);

        return parent::setArchivedAt($archivedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedAt', []);

        return parent::getArchivedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusChangedAt($statusChangedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusChangedAt', [$statusChangedAt]);

        return parent::setStatusChangedAt($statusChangedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusChangedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusChangedAt', []);

        return parent::getStatusChangedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomedirServer($homedirServer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomedirServer', [$homedirServer]);

        return parent::setHomedirServer($homedirServer);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomedirServer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomedirServer', []);

        return parent::getHomedirServer();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomedirFile($homedirFile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomedirFile', [$homedirFile]);

        return parent::setHomedirFile($homedirFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomedirFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomedirFile', []);

        return parent::getHomedirFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomedirOrigSize($homedirOrigSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomedirOrigSize', [$homedirOrigSize]);

        return parent::setHomedirOrigSize($homedirOrigSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomedirOrigSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomedirOrigSize', []);

        return parent::getHomedirOrigSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setHomedirSize($homedirSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHomedirSize', [$homedirSize]);

        return parent::setHomedirSize($homedirSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getHomedirSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHomedirSize', []);

        return parent::getHomedirSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaildirServer($maildirServer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaildirServer', [$maildirServer]);

        return parent::setMaildirServer($maildirServer);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaildirServer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaildirServer', []);

        return parent::getMaildirServer();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaildirFile($maildirFile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaildirFile', [$maildirFile]);

        return parent::setMaildirFile($maildirFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaildirFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaildirFile', []);

        return parent::getMaildirFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaildirOrigSize($maildirOrigSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaildirOrigSize', [$maildirOrigSize]);

        return parent::setMaildirOrigSize($maildirOrigSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaildirOrigSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaildirOrigSize', []);

        return parent::getMaildirOrigSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaildirSize($maildirSize)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaildirSize', [$maildirSize]);

        return parent::setMaildirSize($maildirSize);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaildirSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaildirSize', []);

        return parent::getMaildirSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomain(\Entities\Domain $domain = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomain', [$domain]);

        return parent::setDomain($domain);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomain', []);

        return parent::getDomain();
    }

    /**
     * {@inheritDoc}
     */
    public function setArchivedBy(\Entities\Admin $archivedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArchivedBy', [$archivedBy]);

        return parent::setArchivedBy($archivedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivedBy', []);

        return parent::getArchivedBy();
    }

}
