<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MailboxPreference extends \Entities\MailboxPreference implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'attribute', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'ix', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'op', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'value', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'expire', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'id', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'Mailbox'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'attribute', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'ix', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'op', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'value', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'expire', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'id', '' . "\0" . 'Entities\\MailboxPreference' . "\0" . 'Mailbox'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MailboxPreference $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setAttribute($attribute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttribute', [$attribute]);

        return parent::setAttribute($attribute);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttribute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttribute', []);

        return parent::getAttribute();
    }

    /**
     * {@inheritDoc}
     */
    public function setIx($ix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIx', [$ix]);

        return parent::setIx($ix);
    }

    /**
     * {@inheritDoc}
     */
    public function getIx()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIx', []);

        return parent::getIx();
    }

    /**
     * {@inheritDoc}
     */
    public function setOp($op)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOp', [$op]);

        return parent::setOp($op);
    }

    /**
     * {@inheritDoc}
     */
    public function getOp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOp', []);

        return parent::getOp();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', [$value]);

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', []);

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpire($expire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpire', [$expire]);

        return parent::setExpire($expire);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpire', []);

        return parent::getExpire();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailbox(\Entities\Mailbox $mailbox = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailbox', [$mailbox]);

        return parent::setMailbox($mailbox);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailbox()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailbox', []);

        return parent::getMailbox();
    }

}
